// Curated CFA Level I-style practice questions.
// Authentic exam format: 3 options (A, B, C), each tied to a specific topic /
// learning outcome, with plausible distractors and an explanation.
// Schema matches the app: {id, volume, subject, chapter, chapterTitle,
// difficulty, question, options:[A,B,C], correctIndex (0-2), explanation}.

const CURATED_QUESTIONS = [

  // ───────────────────────── Volume 1 — Quantitative Methods ─────────────────────────
  { id:"q-qm-1", volume:1, subject:"Quantitative Methods", chapter:1, chapterTitle:"Rates and Returns", difficulty:"medium",
    question:"An investor's portfolio earns 15% in Year 1 and loses 5% in Year 2. The geometric mean annual return is closest to:",
    options:["5.00%","4.31%","10.00%"], correctIndex:1,
    explanation:"Geometric mean = [(1.15)(0.95)]^(1/2) − 1 = (1.0925)^0.5 − 1 ≈ 4.31%. It is lower than the 5% arithmetic mean because of return variability." },
  { id:"q-qm-2", volume:1, subject:"Quantitative Methods", chapter:1, chapterTitle:"Rates and Returns", difficulty:"medium",
    question:"Which return measure is most affected by the timing and size of an investor's cash flows into and out of a portfolio?",
    options:["Time-weighted rate of return","Money-weighted rate of return","Geometric mean return"], correctIndex:1,
    explanation:"The money-weighted return is an internal rate of return that is sensitive to the amount and timing of cash flows, which is why time-weighted returns are preferred to evaluate managers." },
  { id:"q-qm-3", volume:1, subject:"Quantitative Methods", chapter:2, chapterTitle:"Time Value of Money in Finance", difficulty:"easy",
    question:"All else equal, an increase in the discount rate used to value a series of future cash flows will:",
    options:["increase their present value","decrease their present value","leave their present value unchanged"], correctIndex:1,
    explanation:"Present value is inversely related to the discount rate; a higher rate discounts future cash flows more heavily, lowering present value." },
  { id:"q-qm-4", volume:1, subject:"Quantitative Methods", chapter:2, chapterTitle:"Time Value of Money in Finance", difficulty:"medium",
    question:"A perpetuity pays $4 annually with the first payment one year from today. If the required return is 8%, its value today is closest to:",
    options:["$32","$50","$54"], correctIndex:1,
    explanation:"Value of an ordinary perpetuity = payment ÷ rate = $4 ÷ 0.08 = $50." },
  { id:"q-qm-5", volume:1, subject:"Quantitative Methods", chapter:3, chapterTitle:"Statistical Measures of Asset Returns", difficulty:"medium",
    question:"A return distribution with a long left tail and a mean less than its median is best described as:",
    options:["positively skewed","negatively skewed","leptokurtic"], correctIndex:1,
    explanation:"A long left tail indicates negative skew; for a negatively skewed distribution the mean is typically less than the median, which is less than the mode." },
  { id:"q-qm-6", volume:1, subject:"Quantitative Methods", chapter:3, chapterTitle:"Statistical Measures of Asset Returns", difficulty:"easy",
    question:"Excess kurtosis greater than zero (a leptokurtic distribution) implies returns that, relative to a normal distribution, have:",
    options:["thinner tails and less peak","fatter tails and more frequent extreme outcomes","perfectly symmetric tails"], correctIndex:1,
    explanation:"Leptokurtic (excess kurtosis > 0) distributions are more peaked with fatter tails, meaning extreme outcomes occur more often than the normal distribution predicts." },
  { id:"q-qm-7", volume:1, subject:"Quantitative Methods", chapter:7, chapterTitle:"Estimation and Inference", difficulty:"medium",
    question:"According to the central limit theorem, as the sample size becomes large, the sampling distribution of the sample mean:",
    options:["approaches a normal distribution regardless of the population's distribution","takes the same shape as the population distribution","becomes uniformly distributed"], correctIndex:0,
    explanation:"The central limit theorem states that the distribution of the sample mean approaches normal as n grows large, even when the underlying population is non-normal." },
  { id:"q-qm-8", volume:1, subject:"Quantitative Methods", chapter:8, chapterTitle:"Hypothesis Testing", difficulty:"medium",
    question:"Rejecting a null hypothesis that is actually true is best described as a:",
    options:["Type I error","Type II error","Type III error"], correctIndex:0,
    explanation:"A Type I error is the false rejection of a true null hypothesis; its probability equals the chosen significance level (α)." },
  { id:"q-qm-9", volume:1, subject:"Quantitative Methods", chapter:8, chapterTitle:"Hypothesis Testing", difficulty:"easy",
    question:"The p-value of a hypothesis test is best interpreted as the:",
    options:["probability that the null hypothesis is true","smallest significance level at which the null hypothesis can be rejected","probability of a Type II error"], correctIndex:1,
    explanation:"The p-value is the smallest level of significance at which the null can be rejected; if the p-value is below α, the null is rejected." },
  { id:"q-qm-10", volume:1, subject:"Quantitative Methods", chapter:10, chapterTitle:"Simple Linear Regression", difficulty:"medium",
    question:"In a simple linear regression, the coefficient of determination (R²) measures the:",
    options:["proportion of the variation in the dependent variable explained by the independent variable","slope of the regression line","correlation between the residuals"], correctIndex:0,
    explanation:"R² is the fraction of the total variation in the dependent variable explained by the independent variable; in simple regression it equals the squared correlation coefficient." },

  // ───────────────────────── Volume 2 — Economics ─────────────────────────
  { id:"q-ec-1", volume:2, subject:"Economics", chapter:1, chapterTitle:"The Firm and Market Structures", difficulty:"medium",
    question:"In a perfectly competitive market in long-run equilibrium, a firm's economic profit is:",
    options:["positive because of barriers to entry","zero because entry and exit drive price to minimum average total cost","maximized where price exceeds marginal cost"], correctIndex:1,
    explanation:"With free entry and exit and identical products, long-run economic profit in perfect competition is driven to zero, with price equal to minimum average total cost." },
  { id:"q-ec-2", volume:2, subject:"Economics", chapter:1, chapterTitle:"The Firm and Market Structures", difficulty:"easy",
    question:"A market with a single seller, high barriers to entry, and a downward-sloping demand curve is best described as a:",
    options:["monopoly","perfectly competitive market","monopolistically competitive market"], correctIndex:0,
    explanation:"A monopoly has one seller facing the entire market demand curve, with high barriers to entry preventing competition." },
  { id:"q-ec-3", volume:2, subject:"Economics", chapter:2, chapterTitle:"Understanding Business Cycles", difficulty:"medium",
    question:"During the contraction phase of a business cycle, which indicator would most likely be rising?",
    options:["Capacity utilization","The unemployment rate","Corporate profits"], correctIndex:1,
    explanation:"In a contraction, economic activity falls; the unemployment rate (a lagging indicator) rises while output, profits, and capacity utilization decline." },
  { id:"q-ec-4", volume:2, subject:"Economics", chapter:3, chapterTitle:"Fiscal Policy", difficulty:"medium",
    question:"Which of the following is most accurately classified as expansionary fiscal policy?",
    options:["A central bank lowering its policy rate","A government increasing spending and cutting taxes","A central bank selling government securities"], correctIndex:1,
    explanation:"Fiscal policy is conducted by the government through spending and taxation; increasing spending and cutting taxes is expansionary. Interest-rate and open-market actions are monetary policy." },
  { id:"q-ec-5", volume:2, subject:"Economics", chapter:4, chapterTitle:"Monetary Policy", difficulty:"medium",
    question:"To reduce inflation, a central bank conducting contractionary monetary policy would most likely:",
    options:["buy government bonds in the open market","raise the policy interest rate","lower reserve requirements"], correctIndex:1,
    explanation:"Contractionary monetary policy raises interest rates (or sells bonds / raises reserve requirements) to slow money growth and reduce inflationary pressure." },
  { id:"q-ec-6", volume:2, subject:"Economics", chapter:6, chapterTitle:"International Trade", difficulty:"medium",
    question:"The theory of comparative advantage states that a country should specialize in producing goods for which it has the:",
    options:["lowest opportunity cost","highest absolute output","largest labor force"], correctIndex:0,
    explanation:"Comparative advantage is based on relative opportunity cost; a country gains from trade by specializing where its opportunity cost of production is lowest." },
  { id:"q-ec-7", volume:2, subject:"Economics", chapter:7, chapterTitle:"Capital Flows and the FX Market", difficulty:"hard",
    question:"The spot USD/EUR rate is 1.1000 and the one-year forward rate is 1.1100. The euro is trading at a forward:",
    options:["premium, and US interest rates are higher than euro rates","discount, and euro interest rates are higher than US rates","premium, and euro interest rates are higher than US rates"], correctIndex:0,
    explanation:"More USD per EUR forward than spot means the euro is at a forward premium. By covered interest rate parity, the currency with the lower interest rate (here the euro) trades at a forward premium, implying US rates are higher." },
  { id:"q-ec-8", volume:2, subject:"Economics", chapter:8, chapterTitle:"Exchange Rate Calculations", difficulty:"medium",
    question:"If the USD/GBP exchange rate moves from 1.25 to 1.30, the British pound has:",
    options:["depreciated against the dollar","appreciated against the dollar","remained unchanged in real terms"], correctIndex:1,
    explanation:"With USD/GBP quoted as dollars per pound, a rise from 1.25 to 1.30 means each pound buys more dollars, so the pound has appreciated against the dollar." },
  { id:"q-ec-9", volume:2, subject:"Economics", chapter:1, chapterTitle:"The Firm and Market Structures", difficulty:"easy",
    question:"If the price elasticity of demand for a good is −0.4, the demand is best described as:",
    options:["elastic","inelastic","unit elastic"], correctIndex:1,
    explanation:"An absolute elasticity less than 1 indicates inelastic demand: quantity demanded changes proportionally less than price." },
  { id:"q-ec-10", volume:2, subject:"Economics", chapter:2, chapterTitle:"Understanding Business Cycles", difficulty:"easy",
    question:"Which measure best captures the change in prices of a fixed basket of consumer goods and services?",
    options:["GDP deflator","Consumer Price Index (CPI)","Producer Price Index (PPI)"], correctIndex:1,
    explanation:"The CPI tracks the price of a fixed consumption basket. The GDP deflator covers all domestically produced goods, and the PPI measures prices received by producers." },

  // ───────────────────────── Volume 3 — Corporate Issuers ─────────────────────────
  { id:"q-ci-1", volume:3, subject:"Corporate Issuers", chapter:5, chapterTitle:"Capital Investments and Capital Allocation", difficulty:"medium",
    question:"When evaluating two mutually exclusive projects, the most theoretically correct decision criterion is to choose the project with the:",
    options:["higher internal rate of return","higher net present value","shorter payback period"], correctIndex:1,
    explanation:"NPV measures the absolute increase in shareholder wealth and is the preferred criterion for mutually exclusive projects; IRR can rank them incorrectly when scale or timing differs." },
  { id:"q-ci-2", volume:3, subject:"Corporate Issuers", chapter:6, chapterTitle:"Capital Structure", difficulty:"hard",
    question:"Under Modigliani–Miller with no taxes, increasing financial leverage will:",
    options:["increase firm value by lowering the WACC","leave firm value unchanged because the cost of equity rises with leverage","decrease firm value due to bankruptcy costs"], correctIndex:1,
    explanation:"With no taxes and perfect markets, capital structure is irrelevant: as cheaper debt is added, the cost of equity rises to keep WACC and firm value constant." },
  { id:"q-ci-3", volume:3, subject:"Corporate Issuers", chapter:6, chapterTitle:"Capital Structure", difficulty:"medium",
    question:"Adding the tax-deductibility of interest to the Modigliani–Miller framework implies that, up to a point, using more debt:",
    options:["reduces firm value","increases firm value through the interest tax shield","has no effect on the cost of capital"], correctIndex:1,
    explanation:"Because interest is tax-deductible, debt creates a tax shield that lowers WACC and raises firm value, until offset by rising financial distress costs." },
  { id:"q-ci-4", volume:3, subject:"Corporate Issuers", chapter:4, chapterTitle:"Working Capital and Liquidity", difficulty:"easy",
    question:"A company's cash conversion cycle is best reduced by:",
    options:["lengthening the number of days of payables and collecting receivables faster","increasing days of inventory on hand","paying suppliers earlier than required"], correctIndex:0,
    explanation:"Cash conversion cycle = days inventory + days receivables − days payables. Collecting receivables faster and extending payables both shorten the cycle." },
  { id:"q-ci-5", volume:3, subject:"Corporate Issuers", chapter:2, chapterTitle:"Investors and Other Stakeholders", difficulty:"medium",
    question:"The conflict of interest that arises when managers act in their own interest rather than shareholders' is best described as a(n):",
    options:["principal–agent problem","information cascade","winner's curse"], correctIndex:0,
    explanation:"The principal–agent (agency) problem describes the conflict between owners (principals) and managers (agents) whose incentives may diverge." },
  { id:"q-ci-6", volume:3, subject:"Corporate Issuers", chapter:3, chapterTitle:"Corporate Governance: Conflicts, Mechanisms, Risks, and Benefits", difficulty:"easy",
    question:"Strong corporate governance most directly benefits a company by:",
    options:["guaranteeing higher reported earnings","reducing agency costs and the risk of value-destroying decisions","eliminating all business risk"], correctIndex:1,
    explanation:"Effective governance aligns management with stakeholder interests, reducing agency costs and the likelihood of poor or self-serving decisions; it cannot remove business risk." },
  { id:"q-ci-7", volume:3, subject:"Corporate Issuers", chapter:1, chapterTitle:"Organizational Forms, Corporate Issuer Features, and Ownership", difficulty:"easy",
    question:"A key feature distinguishing a corporation from a sole proprietorship is that the corporation:",
    options:["offers owners limited liability","cannot raise external capital","is always exempt from taxation"], correctIndex:0,
    explanation:"Shareholders of a corporation enjoy limited liability—their loss is limited to their investment—unlike a sole proprietor, who is personally liable for business debts." },
  { id:"q-ci-8", volume:3, subject:"Corporate Issuers", chapter:5, chapterTitle:"Capital Investments and Capital Allocation", difficulty:"medium",
    question:"A project should be accepted on a stand-alone basis when its:",
    options:["IRR is less than the required rate of return","NPV is greater than zero","payback period exceeds the project's life"], correctIndex:1,
    explanation:"A positive NPV means the project earns more than its cost of capital and adds value, which corresponds to an IRR greater than the required return." },
  { id:"q-ci-9", volume:3, subject:"Corporate Issuers", chapter:7, chapterTitle:"Business Models", difficulty:"easy",
    question:"A company's business model is best described as how the company:",
    options:["records transactions under accounting standards","creates, delivers, and captures value","finances its long-term assets"], correctIndex:1,
    explanation:"A business model describes the firm's value proposition—how it creates, delivers, and captures value for customers and owners—rather than its accounting or financing." },
  { id:"q-ci-10", volume:3, subject:"Corporate Issuers", chapter:6, chapterTitle:"Capital Structure", difficulty:"medium",
    question:"According to the pecking order theory, a profitable company seeking funds will most prefer to use:",
    options:["new equity issuance","internally generated funds","subordinated debt"], correctIndex:1,
    explanation:"Pecking order theory ranks financing by information-cost: internal funds first, then debt, and new equity only as a last resort." },

  // ───────────────────────── Volume 4 — Financial Statement Analysis ─────────────────────────
  { id:"q-fsa-1", volume:4, subject:"Financial Statement Analysis", chapter:6, chapterTitle:"Analysis of Inventories", difficulty:"hard",
    question:"During a period of rising prices, a company using LIFO rather than FIFO will most likely report:",
    options:["higher net income and higher ending inventory","lower net income and lower ending inventory","higher ending inventory and lower cost of goods sold"], correctIndex:1,
    explanation:"With rising prices, LIFO charges newer, higher costs to COGS—raising COGS and lowering both net income and ending inventory relative to FIFO." },
  { id:"q-fsa-2", volume:4, subject:"Financial Statement Analysis", chapter:11, chapterTitle:"Financial Analysis Techniques", difficulty:"medium",
    question:"Using the DuPont analysis, return on equity (ROE) can be decomposed as the product of net profit margin, total asset turnover, and:",
    options:["the financial leverage (equity multiplier)","the current ratio","the interest coverage ratio"], correctIndex:0,
    explanation:"The three-part DuPont identity is ROE = net profit margin × asset turnover × financial leverage (assets/equity)." },
  { id:"q-fsa-3", volume:4, subject:"Financial Statement Analysis", chapter:4, chapterTitle:"Analyzing Statements of Cash Flows I", difficulty:"medium",
    question:"Under US GAAP, interest paid on debt is most likely classified in the statement of cash flows as a(n):",
    options:["financing activity","operating activity","investing activity"], correctIndex:1,
    explanation:"Under US GAAP, interest paid is reported as an operating cash flow. (Under IFRS it may be classified as operating or financing.)" },
  { id:"q-fsa-4", volume:4, subject:"Financial Statement Analysis", chapter:2, chapterTitle:"Analyzing Income Statements", difficulty:"medium",
    question:"Under the accrual basis of accounting, revenue is recognized when:",
    options:["cash is received from the customer","the performance obligation is satisfied","the related expenses are paid"], correctIndex:1,
    explanation:"Accrual accounting recognizes revenue when the performance obligation is satisfied (control transfers to the customer), not necessarily when cash changes hands." },
  { id:"q-fsa-5", volume:4, subject:"Financial Statement Analysis", chapter:9, chapterTitle:"Analysis of Income Taxes", difficulty:"hard",
    question:"A deferred tax liability most commonly arises when:",
    options:["taxable income exceeds pretax accounting income","accounting depreciation exceeds tax depreciation","tax depreciation exceeds accounting depreciation in early years"], correctIndex:2,
    explanation:"Using accelerated depreciation for tax but straight-line for reporting makes tax depreciation higher early on, lowering current taxes payable and creating a deferred tax liability." },
  { id:"q-fsa-6", volume:4, subject:"Financial Statement Analysis", chapter:11, chapterTitle:"Financial Analysis Techniques", difficulty:"easy",
    question:"Which ratio best measures a company's ability to meet its short-term obligations using its most liquid assets?",
    options:["Quick ratio","Debt-to-equity ratio","Gross profit margin"], correctIndex:0,
    explanation:"The quick (acid-test) ratio compares the most liquid current assets (excluding inventory) to current liabilities, gauging short-term liquidity." },
  { id:"q-fsa-7", volume:4, subject:"Financial Statement Analysis", chapter:3, chapterTitle:"Analyzing Balance Sheets", difficulty:"easy",
    question:"Which of the following is most accurately classified as a non-current liability?",
    options:["Accounts payable","Bonds payable due in five years","Accrued wages"], correctIndex:1,
    explanation:"Bonds payable maturing in five years are a long-term (non-current) liability; accounts payable and accrued wages are current liabilities." },
  { id:"q-fsa-8", volume:4, subject:"Financial Statement Analysis", chapter:5, chapterTitle:"Analyzing Statements of Cash Flows II", difficulty:"medium",
    question:"Compared with the indirect method, the direct method of presenting cash flow from operations:",
    options:["reports the same total but shows specific operating cash receipts and payments","always reports a higher cash flow from operations","starts from net income and adjusts for non-cash items"], correctIndex:0,
    explanation:"Both methods yield the same total operating cash flow; the direct method lists actual cash receipts and payments, while the indirect method reconciles from net income." },
  { id:"q-fsa-9", volume:4, subject:"Financial Statement Analysis", chapter:7, chapterTitle:"Analysis of Long-Term Assets", difficulty:"medium",
    question:"Capitalizing rather than expensing a cost will, in the year of the expenditure, most likely result in:",
    options:["lower net income and lower assets","higher net income and higher assets","higher cash flow from operations only because of higher taxes"], correctIndex:1,
    explanation:"Capitalizing defers the cost to future periods via depreciation, so current-year expenses are lower and net income and total assets are higher than if expensed." },
  { id:"q-fsa-10", volume:4, subject:"Financial Statement Analysis", chapter:10, chapterTitle:"Financial Reporting Quality", difficulty:"easy",
    question:"High-quality financial reporting is best described as information that is:",
    options:["decision-useful, being both relevant and faithfully representative","always conservative to understate earnings","designed to maximize reported net income"], correctIndex:0,
    explanation:"High reporting quality means information is decision-useful: relevant and a faithful representation of economic reality, not biased toward any earnings outcome." },

  // ───────────────────────── Volume 5 — Equity Investments ─────────────────────────
  { id:"q-eq-1", volume:5, subject:"Equity Investments", chapter:2, chapterTitle:"Security Market Indexes", difficulty:"hard",
    question:"A price-weighted equity index is most affected by a given percentage price change in a constituent stock that has the:",
    options:["largest market capitalization","highest share price","greatest number of shares outstanding"], correctIndex:1,
    explanation:"In a price-weighted index, weights are proportional to share price, so the highest-priced stock has the greatest influence regardless of company size." },
  { id:"q-eq-2", volume:5, subject:"Equity Investments", chapter:3, chapterTitle:"Market Efficiency", difficulty:"medium",
    question:"If markets are semi-strong-form efficient, an investor cannot consistently earn abnormal returns using:",
    options:["only material non-public information","any publicly available information, including financial statements","past price and volume data only"], correctIndex:1,
    explanation:"Semi-strong-form efficiency means prices reflect all public information, so fundamental analysis of public data cannot produce consistent abnormal returns; only private information might." },
  { id:"q-eq-3", volume:5, subject:"Equity Investments", chapter:8, chapterTitle:"Equity Valuation: Concepts and Basic Tools", difficulty:"hard",
    question:"A stock just paid a dividend of $2.00, expected to grow at 4% indefinitely. If the required return is 10%, the Gordon growth model value is closest to:",
    options:["$33.33","$34.67","$20.00"], correctIndex:1,
    explanation:"Value = D1 / (r − g) = (2.00 × 1.04) / (0.10 − 0.04) = 2.08 / 0.06 ≈ $34.67." },
  { id:"q-eq-4", volume:5, subject:"Equity Investments", chapter:8, chapterTitle:"Equity Valuation: Concepts and Basic Tools", difficulty:"medium",
    question:"The Gordon (constant) growth dividend discount model is least appropriate for valuing a company that:",
    options:["pays stable, predictable dividends","has a dividend growth rate exceeding its required return","is mature with a sustainable payout ratio"], correctIndex:1,
    explanation:"The model requires the required return to exceed the growth rate; if g ≥ r the formula produces a negative or undefined value, making it inapplicable to high-growth firms." },
  { id:"q-eq-5", volume:5, subject:"Equity Investments", chapter:4, chapterTitle:"Overview of Equity Securities", difficulty:"easy",
    question:"Compared with common shareholders, holders of cumulative preferred shares:",
    options:["have a residual claim on earnings","are entitled to any unpaid prior dividends before common dividends are paid","always have voting rights"], correctIndex:1,
    explanation:"Cumulative preferred dividends in arrears must be paid before any common dividend; preferred holders generally rank ahead of common but usually lack voting rights." },
  { id:"q-eq-6", volume:5, subject:"Equity Investments", chapter:6, chapterTitle:"Industry and Competitive Analysis", difficulty:"medium",
    question:"In Porter's five forces framework, an industry with high barriers to entry and few substitute products is most likely to have:",
    options:["greater pricing power and higher profitability","intense price competition","low returns on invested capital"], correctIndex:0,
    explanation:"High entry barriers and few substitutes reduce competitive pressure, giving incumbents more pricing power and the potential for higher, more sustainable profitability." },
  { id:"q-eq-7", volume:5, subject:"Equity Investments", chapter:1, chapterTitle:"Market Organization and Structure", difficulty:"easy",
    question:"An investor who buys stock on margin is most exposed to a margin call when the:",
    options:["stock price rises sharply","stock price falls and equity drops below the maintenance margin","dividend yield increases"], correctIndex:1,
    explanation:"Buying on margin uses borrowed funds; if the price falls and the investor's equity drops below the maintenance margin, a margin call requires additional funds." },
  { id:"q-eq-8", volume:5, subject:"Equity Investments", chapter:8, chapterTitle:"Equity Valuation: Concepts and Basic Tools", difficulty:"medium",
    question:"A price-to-earnings (P/E) multiple is an example of which valuation approach?",
    options:["Present-value (discounted cash flow) model","Relative valuation using multiples","Asset-based valuation"], correctIndex:1,
    explanation:"P/E is a relative-valuation (multiples) method that compares a stock's price to a fundamental such as earnings, rather than discounting cash flows or valuing net assets." },
  { id:"q-eq-9", volume:5, subject:"Equity Investments", chapter:2, chapterTitle:"Security Market Indexes", difficulty:"medium",
    question:"Most broad-market equity indexes today are constructed using:",
    options:["price weighting","float-adjusted market-capitalization weighting","equal weighting"], correctIndex:1,
    explanation:"Float-adjusted market-cap weighting reflects the investable value of constituents and is the most common method for broad equity indexes." },
  { id:"q-eq-10", volume:5, subject:"Equity Investments", chapter:3, chapterTitle:"Market Efficiency", difficulty:"easy",
    question:"The existence of which anomaly would be least consistent with weak-form market efficiency?",
    options:["Profits from trading on patterns in past prices","Slow price reaction to earnings announcements","Higher long-run returns to value stocks"], correctIndex:0,
    explanation:"Weak-form efficiency holds that past price data cannot generate abnormal returns; consistently profiting from price patterns would violate it." },

  // ───────────────────────── Volume 6 — Fixed Income ─────────────────────────
  { id:"q-fi-1", volume:6, subject:"Fixed Income", chapter:6, chapterTitle:"Fixed-Income Bond Valuation: Prices and Yields", difficulty:"easy",
    question:"A bond will trade at a premium to par when its coupon rate is:",
    options:["greater than its market yield-to-maturity","less than its market yield-to-maturity","equal to its market yield-to-maturity"], correctIndex:0,
    explanation:"When the coupon rate exceeds the required yield, the bond's cash flows are worth more than par, so it trades at a premium." },
  { id:"q-fi-2", volume:6, subject:"Fixed Income", chapter:10, chapterTitle:"Interest Rate Risk and Return", difficulty:"medium",
    question:"All else equal, which bond has the greatest interest rate price sensitivity (highest duration)?",
    options:["A high-coupon, short-maturity bond","A low-coupon, long-maturity bond","A high-coupon, long-maturity bond"], correctIndex:1,
    explanation:"Duration rises with maturity and falls with coupon, so a low-coupon, long-maturity bond is the most price-sensitive to yield changes." },
  { id:"q-fi-3", volume:6, subject:"Fixed Income", chapter:11, chapterTitle:"Yield-Based Bond Duration Measures and Properties", difficulty:"medium",
    question:"A bond has a modified duration of 6.0. If its yield rises by 50 basis points, the estimated percentage price change is closest to:",
    options:["−3.0%","+3.0%","−0.5%"], correctIndex:0,
    explanation:"%ΔPrice ≈ −modified duration × Δyield = −6.0 × 0.50% = −3.0%." },
  { id:"q-fi-4", volume:6, subject:"Fixed Income", chapter:12, chapterTitle:"Yield-Based Bond Convexity and Portfolio Properties", difficulty:"hard",
    question:"Incorporating convexity into the estimate of a bond's price change for a large change in yield will, relative to using duration alone:",
    options:["always lower the estimated new price","produce a higher estimated price for both yield increases and decreases","ignore the curvature of the price-yield relationship"], correctIndex:1,
    explanation:"Positive convexity adds a positive term to the price-change estimate, so the convexity-adjusted price is higher than the duration-only estimate for both upward and downward yield moves." },
  { id:"q-fi-5", volume:6, subject:"Fixed Income", chapter:14, chapterTitle:"Credit Risk", difficulty:"medium",
    question:"The risk that a bond issuer fails to make timely interest or principal payments is best described as:",
    options:["interest rate risk","default (credit) risk","reinvestment risk"], correctIndex:1,
    explanation:"Default risk is the possibility the issuer does not pay interest or principal as promised; it is a component of credit risk." },
  { id:"q-fi-6", volume:6, subject:"Fixed Income", chapter:1, chapterTitle:"Fixed-Income Instrument Features", difficulty:"easy",
    question:"A bond's indenture is best described as the:",
    options:["legal contract specifying the issuer's obligations and bondholders' rights","schedule of expected reinvestment rates","credit rating assigned by an agency"], correctIndex:0,
    explanation:"The indenture (trust deed) is the legal contract between issuer and bondholders that sets out the bond's features, covenants, and the parties' rights and obligations." },
  { id:"q-fi-7", volume:6, subject:"Fixed Income", chapter:9, chapterTitle:"The Term Structure of Interest Rates: Spot, Par, and Forward Curves", difficulty:"hard",
    question:"A spot rate is best defined as the:",
    options:["yield on a coupon-paying bond held to maturity","yield on a zero-coupon bond for a given maturity","expected future short-term rate"], correctIndex:1,
    explanation:"A spot rate is the yield on a single payment (zero-coupon) for a specific maturity; coupon bonds can be valued as portfolios of zero-coupon cash flows discounted at spot rates." },
  { id:"q-fi-8", volume:6, subject:"Fixed Income", chapter:6, chapterTitle:"Fixed-Income Bond Valuation: Prices and Yields", difficulty:"medium",
    question:"Holding price constant, the relationship between a bond's price and its yield-to-maturity is best described as:",
    options:["positive and linear","inverse and convex","unrelated"], correctIndex:1,
    explanation:"Bond prices fall as yields rise (inverse relationship), and the price-yield curve is convex rather than a straight line." },
  { id:"q-fi-9", volume:6, subject:"Fixed Income", chapter:17, chapterTitle:"Fixed-Income Securitization", difficulty:"medium",
    question:"A primary benefit of securitization to the financial system is that it:",
    options:["eliminates credit risk from the underlying loans","increases the liquidity of otherwise illiquid assets and broadens funding sources","guarantees higher yields to all investors"], correctIndex:1,
    explanation:"Securitization pools illiquid loans into tradable securities, improving liquidity and giving issuers access to a wider investor base; it redistributes—rather than eliminates—credit risk." },
  { id:"q-fi-10", volume:6, subject:"Fixed Income", chapter:10, chapterTitle:"Interest Rate Risk and Return", difficulty:"medium",
    question:"For a bond held to maturity, a rise in market interest rates after purchase will most likely:",
    options:["decrease total return because coupons are reinvested at lower rates","increase total return because coupons are reinvested at higher rates","have no effect on realized return"], correctIndex:1,
    explanation:"For an investor holding to maturity, higher reinvestment rates raise the future value of reinvested coupons, increasing the realized return (the reinvestment effect)." },

  // ───────────────────────── Volume 7 — Derivatives ─────────────────────────
  { id:"q-de-1", volume:7, subject:"Derivatives", chapter:5, chapterTitle:"Pricing and Valuation of Forward Contracts", difficulty:"medium",
    question:"At initiation of a standard forward contract with no upfront payment, the value of the contract to each party is:",
    options:["equal to the forward price","zero","equal to the spot price"], correctIndex:1,
    explanation:"A forward is priced so that no cash changes hands at initiation; the contract's value is zero at inception and changes as the underlying price moves." },
  { id:"q-de-2", volume:7, subject:"Derivatives", chapter:6, chapterTitle:"Pricing and Valuation of Futures Contracts", difficulty:"medium",
    question:"A key difference between futures and forward contracts is that futures:",
    options:["are customized and traded over the counter","are marked to market daily through a clearinghouse","cannot be closed out before expiration"], correctIndex:1,
    explanation:"Futures are exchange-traded, standardized, and marked to market daily via a clearinghouse, which reduces counterparty risk relative to customized OTC forwards." },
  { id:"q-de-3", volume:7, subject:"Derivatives", chapter:8, chapterTitle:"Pricing and Valuation of Options", difficulty:"easy",
    question:"The intrinsic value of a call option is best described as the greater of zero and the:",
    options:["underlying price minus the exercise price","exercise price minus the underlying price","option premium minus time value"], correctIndex:0,
    explanation:"A call's intrinsic value is max(0, S − X): the amount by which the underlying price exceeds the exercise price." },
  { id:"q-de-4", volume:7, subject:"Derivatives", chapter:9, chapterTitle:"Option Replication Using Put-Call Parity", difficulty:"hard",
    question:"Put-call parity states that a fiduciary call (long call plus risk-free bond) has the same value as a protective put, which is a long put plus a:",
    options:["short position in the underlying","long position in the underlying asset","short call option"], correctIndex:1,
    explanation:"Put-call parity: C + X/(1+r)^T = P + S. The protective put combines a long put with a long position in the underlying, equaling the fiduciary call." },
  { id:"q-de-5", volume:7, subject:"Derivatives", chapter:1, chapterTitle:"Derivative Instrument and Derivative Market Features", difficulty:"easy",
    question:"A derivative is best defined as a financial instrument whose value is:",
    options:["independent of any other asset","derived from the value of an underlying asset, rate, or index","always equal to its notional amount"], correctIndex:1,
    explanation:"A derivative derives its value from an underlying asset, reference rate, or index, rather than having independent intrinsic value." },
  { id:"q-de-6", volume:7, subject:"Derivatives", chapter:8, chapterTitle:"Pricing and Valuation of Options", difficulty:"medium",
    question:"All else equal, an increase in the volatility of the underlying asset will most likely:",
    options:["increase the values of both call and put options","decrease the value of call options only","leave option values unchanged"], correctIndex:0,
    explanation:"Greater volatility raises the probability of larger favorable moves, increasing the value of both calls and puts (option values are increasing in volatility)." },
  { id:"q-de-7", volume:7, subject:"Derivatives", chapter:7, chapterTitle:"Pricing and Valuation of Interest Rates and Other Swaps", difficulty:"medium",
    question:"A plain-vanilla interest rate swap can be most accurately described as an exchange of:",
    options:["fixed interest payments for floating interest payments on a notional amount","principal amounts in two currencies","equity returns for a fixed coupon"], correctIndex:0,
    explanation:"In a plain-vanilla interest rate swap, one party pays fixed and receives floating (and vice versa) on a notional principal; the notional is generally not exchanged." },
  { id:"q-de-8", volume:7, subject:"Derivatives", chapter:4, chapterTitle:"Arbitrage, Replication, and the Cost of Carry in Pricing Derivatives", difficulty:"hard",
    question:"The no-arbitrage forward price of a non-dividend-paying asset is the spot price:",
    options:["compounded at the risk-free rate to the delivery date","discounted at the risk-free rate","minus the expected future spot price"], correctIndex:0,
    explanation:"By cost-of-carry/no-arbitrage, F0 = S0 × (1 + r)^T for a non-dividend-paying asset: the spot price carried forward at the risk-free rate." },
  { id:"q-de-9", volume:7, subject:"Derivatives", chapter:3, chapterTitle:"Derivative Benefits, Risks, and Issuer and Investor Uses", difficulty:"easy",
    question:"A primary economic benefit of derivatives is that they allow market participants to:",
    options:["eliminate all investment risk","transfer and manage risk efficiently at low cost","guarantee positive returns"], correctIndex:1,
    explanation:"Derivatives enable efficient risk transfer (hedging) and price discovery at relatively low cost; they reallocate risk rather than removing it." },
  { id:"q-de-10", volume:7, subject:"Derivatives", chapter:8, chapterTitle:"Pricing and Valuation of Options", difficulty:"easy",
    question:"A put option is in the money when the:",
    options:["underlying price is above the exercise price","underlying price is below the exercise price","option premium equals the intrinsic value"], correctIndex:1,
    explanation:"A put gives the right to sell at the exercise price, so it is in the money when the underlying trades below that exercise price." },

  // ───────────────────────── Volume 8 — Alternative Investments ─────────────────────────
  { id:"q-ai-1", volume:8, subject:"Alternative Investments", chapter:6, chapterTitle:"Hedge Funds", difficulty:"medium",
    question:"Under a '2 and 20' hedge fund fee structure, the '20' refers to the:",
    options:["annual management fee on assets","incentive fee charged on profits","redemption fee on withdrawals"], correctIndex:1,
    explanation:"In '2 and 20', 2% is the annual management fee on assets and 20% is the incentive (performance) fee charged on profits, often subject to a hurdle and high-water mark." },
  { id:"q-ai-2", volume:8, subject:"Alternative Investments", chapter:6, chapterTitle:"Hedge Funds", difficulty:"medium",
    question:"A high-water mark provision in a hedge fund fee structure ensures that the manager:",
    options:["earns incentive fees only on cumulative new profits above the prior peak NAV","charges management fees only when returns are positive","never returns capital to investors"], correctIndex:0,
    explanation:"A high-water mark requires the fund to recover prior losses before incentive fees are charged again, so the manager is paid only on net new gains above the previous peak." },
  { id:"q-ai-3", volume:8, subject:"Alternative Investments", chapter:3, chapterTitle:"Investments in Private Capital: Equity and Debt", difficulty:"medium",
    question:"A leveraged buyout (LBO) is a private equity strategy that most typically involves:",
    options:["acquiring a company primarily using debt financing","providing seed capital to early-stage startups","buying distressed bonds at a discount"], correctIndex:0,
    explanation:"An LBO uses a large proportion of debt to acquire a company, aiming to improve operations and repay debt before exiting; venture capital funds early-stage startups." },
  { id:"q-ai-4", volume:8, subject:"Alternative Investments", chapter:1, chapterTitle:"Alternative Investment Features, Methods, and Structures", difficulty:"easy",
    question:"Compared with traditional investments, alternative investments are generally characterized by:",
    options:["high liquidity and daily pricing","lower liquidity, higher fees, and limited transparency","guaranteed downside protection"], correctIndex:1,
    explanation:"Alternatives typically feature lower liquidity, higher and more complex fees, and less transparency, along with potential diversification benefits." },
  { id:"q-ai-5", volume:8, subject:"Alternative Investments", chapter:5, chapterTitle:"Natural Resources", difficulty:"medium",
    question:"An investor seeking commodity exposure without holding the physical asset would most likely use:",
    options:["commodity futures contracts","direct ownership of farmland","a private equity fund"], correctIndex:0,
    explanation:"Commodity futures provide exposure to commodity price movements without the costs of storing and transporting the physical commodity." },
  { id:"q-ai-6", volume:8, subject:"Alternative Investments", chapter:4, chapterTitle:"Real Estate and Infrastructure", difficulty:"easy",
    question:"A publicly traded REIT most directly offers investors:",
    options:["liquid exposure to a portfolio of real estate assets","a guaranteed fixed coupon like a bond","ownership of a single private building with no market price"], correctIndex:0,
    explanation:"A publicly traded REIT gives liquid, exchange-traded exposure to a diversified pool of income-producing real estate." },
  { id:"q-ai-7", volume:8, subject:"Alternative Investments", chapter:7, chapterTitle:"Introduction to Digital Assets", difficulty:"easy",
    question:"Distributed ledger technology underlying many digital assets is best described as a:",
    options:["centralized database controlled by a single bank","shared, cryptographically secured record maintained across a network","government-issued physical currency"], correctIndex:1,
    explanation:"Distributed ledger (blockchain) technology maintains a shared, tamper-resistant record across many participants without a single central authority." },
  { id:"q-ai-8", volume:8, subject:"Alternative Investments", chapter:2, chapterTitle:"Alternative Investment Performance and Returns", difficulty:"hard",
    question:"Survivorship bias in reported hedge fund index returns most likely causes the index to:",
    options:["understate average returns and overstate risk","overstate average returns because failed funds drop out","have no effect on reported performance"], correctIndex:1,
    explanation:"When poorly performing funds close and leave the index, the surviving funds' returns overstate the average performance of the original universe." },
  { id:"q-ai-9", volume:8, subject:"Alternative Investments", chapter:3, chapterTitle:"Investments in Private Capital: Equity and Debt", difficulty:"medium",
    question:"Committed capital that a private equity fund has not yet called from its limited partners is referred to as:",
    options:["carried interest","dry powder","clawback"], correctIndex:1,
    explanation:"'Dry powder' is committed but uncalled capital available for the fund to deploy in future investments." },
  { id:"q-ai-10", volume:8, subject:"Alternative Investments", chapter:1, chapterTitle:"Alternative Investment Features, Methods, and Structures", difficulty:"easy",
    question:"A key reason institutional investors add alternatives to a traditional stock-and-bond portfolio is to:",
    options:["increase correlation with equities","obtain potential diversification and return enhancement","guarantee liquidity during crises"], correctIndex:1,
    explanation:"Alternatives are added mainly for diversification (low correlation with traditional assets) and potential return enhancement, not for liquidity." },

  // ───────────────────────── Volume 9 — Portfolio Management ─────────────────────────
  { id:"q-pm-1", volume:9, subject:"Portfolio Management", chapter:1, chapterTitle:"Portfolio Risk and Return: Part I", difficulty:"hard",
    question:"Combining two risky assets that are less than perfectly positively correlated will most likely produce a portfolio whose standard deviation is:",
    options:["the weighted average of the two assets' standard deviations","less than the weighted average of the two assets' standard deviations","greater than either asset's standard deviation"], correctIndex:1,
    explanation:"Whenever correlation is below +1, diversification reduces portfolio standard deviation below the weighted average of the components' standard deviations." },
  { id:"q-pm-2", volume:9, subject:"Portfolio Management", chapter:1, chapterTitle:"Portfolio Risk and Return: Part I", difficulty:"medium",
    question:"According to the capital asset pricing model (CAPM), the expected return on a security is determined by its:",
    options:["total risk as measured by standard deviation","systematic risk as measured by beta","unsystematic (firm-specific) risk"], correctIndex:1,
    explanation:"CAPM holds that only non-diversifiable systematic risk (beta) is priced; investors are not rewarded for diversifiable, firm-specific risk." },
  { id:"q-pm-3", volume:9, subject:"Portfolio Management", chapter:2, chapterTitle:"Portfolio Risk and Return: Part II", difficulty:"hard",
    question:"A stock has a beta of 1.2. If the risk-free rate is 3% and the expected market return is 8%, the CAPM required return is closest to:",
    options:["9.0%","11.0%","6.6%"], correctIndex:0,
    explanation:"Required return = Rf + β(Rm − Rf) = 3% + 1.2 × (8% − 3%) = 3% + 6% = 9.0%." },
  { id:"q-pm-4", volume:9, subject:"Portfolio Management", chapter:2, chapterTitle:"Portfolio Risk and Return: Part II", difficulty:"medium",
    question:"On the security market line (SML), a stock plotting above the line is best described as:",
    options:["overvalued, offering too little return for its risk","undervalued, offering more return than required for its risk","fairly valued"], correctIndex:1,
    explanation:"A security plotting above the SML offers a higher expected return than CAPM requires for its beta, indicating it is undervalued." },
  { id:"q-pm-5", volume:9, subject:"Portfolio Management", chapter:4, chapterTitle:"Basics of Portfolio Planning and Construction", difficulty:"medium",
    question:"In an investment policy statement, a client's time horizon and liquidity needs are best classified as:",
    options:["return objectives","constraints","risk objectives"], correctIndex:1,
    explanation:"An IPS separates objectives (return and risk) from constraints; time horizon, liquidity, taxes, legal/regulatory factors, and unique circumstances are constraints." },
  { id:"q-pm-6", volume:9, subject:"Portfolio Management", chapter:5, chapterTitle:"The Behavioral Biases of Individuals", difficulty:"medium",
    question:"An investor who holds losing positions too long to avoid realizing a loss is exhibiting:",
    options:["loss aversion","representativeness","anchoring"], correctIndex:0,
    explanation:"Loss aversion—feeling losses more intensely than equivalent gains—leads investors to hold losers too long and sell winners too soon (the disposition effect)." },
  { id:"q-pm-7", volume:9, subject:"Portfolio Management", chapter:3, chapterTitle:"Portfolio Management: An Overview", difficulty:"easy",
    question:"The primary advantage of the portfolio perspective is that it emphasizes:",
    options:["picking individual securities with the highest returns","evaluating risk and return at the aggregate portfolio level","minimizing the number of holdings"], correctIndex:1,
    explanation:"The portfolio perspective evaluates investments by their contribution to overall portfolio risk and return, recognizing diversification effects rather than judging securities in isolation." },
  { id:"q-pm-8", volume:9, subject:"Portfolio Management", chapter:1, chapterTitle:"Portfolio Risk and Return: Part I", difficulty:"medium",
    question:"The capital market line (CML) describes the risk-return combinations available from portfolios that combine the risk-free asset with the:",
    options:["minimum-variance portfolio","market (tangency) portfolio of risky assets","single security with the highest Sharpe ratio"], correctIndex:1,
    explanation:"The CML connects the risk-free asset to the market (tangency) portfolio; all efficient portfolios under the CML are combinations of these two." },
  { id:"q-pm-9", volume:9, subject:"Portfolio Management", chapter:6, chapterTitle:"Introduction to Risk Management", difficulty:"easy",
    question:"A risk management framework's first step is most appropriately to:",
    options:["transfer all risks through insurance","identify and measure the risks the organization faces","eliminate every risk exposure"], correctIndex:1,
    explanation:"Effective risk management begins with identifying and measuring exposures relative to the organization's risk tolerance before deciding how to modify them." },
  { id:"q-pm-10", volume:9, subject:"Portfolio Management", chapter:2, chapterTitle:"Portfolio Risk and Return: Part II", difficulty:"easy",
    question:"Unsystematic risk is best described as risk that:",
    options:["cannot be reduced through diversification","is specific to a company or industry and can be diversified away","is compensated by a higher expected return"], correctIndex:1,
    explanation:"Unsystematic (firm-specific) risk can be eliminated through diversification, so the market does not reward investors for bearing it." },

  // ───────────────────────── Volume 10 — Ethical & Professional Standards ─────────────────────────
  { id:"q-eth-1", volume:10, subject:"Ethical & Professional Standards", chapter:2, chapterTitle:"Code of Ethics and Standards of Professional Conduct", difficulty:"medium",
    question:"A member who learns material nonpublic information about a pending acquisition and trades on it most likely violates the Standard concerning:",
    options:["Material Nonpublic Information (Integrity of Capital Markets)","Loyalty to Employer","Independence and Objectivity"], correctIndex:0,
    explanation:"Standard II(A) Material Nonpublic Information prohibits members from acting or causing others to act on material nonpublic information that could affect a security's value." },
  { id:"q-eth-2", volume:10, subject:"Ethical & Professional Standards", chapter:3, chapterTitle:"Guidance for Standards I-VII", difficulty:"medium",
    question:"When a member's employer has no formal policy on accepting gifts from clients, accepting a lavish gift contingent on future performance would most directly implicate the Standard on:",
    options:["Independence and Objectivity","Performance Presentation","Record Retention"], correctIndex:0,
    explanation:"Gifts that could compromise a member's objectivity—especially performance-contingent ones from clients—implicate Standard I(B) Independence and Objectivity." },
  { id:"q-eth-3", volume:10, subject:"Ethical & Professional Standards", chapter:3, chapterTitle:"Guidance for Standards I-VII", difficulty:"medium",
    question:"Distributing a new investment recommendation to favored clients before all clients is a violation of the Standard on:",
    options:["Fair Dealing","Suitability","Diligence and Reasonable Basis"], correctIndex:0,
    explanation:"Standard III(B) Fair Dealing requires members to treat all clients fairly when disseminating investment recommendations or taking investment action." },
  { id:"q-eth-4", volume:10, subject:"Ethical & Professional Standards", chapter:3, chapterTitle:"Guidance for Standards I-VII", difficulty:"easy",
    question:"Before making an investment recommendation to a client, determining that it fits the client's objectives and circumstances is required by the Standard on:",
    options:["Suitability","Misrepresentation","Loyalty, Prudence, and Care"], correctIndex:0,
    explanation:"Standard III(C) Suitability requires that recommendations and actions be appropriate for the client's financial situation, objectives, and constraints." },
  { id:"q-eth-5", volume:10, subject:"Ethical & Professional Standards", chapter:3, chapterTitle:"Guidance for Standards I-VII", difficulty:"medium",
    question:"Guaranteeing a specific investment return to attract a client most directly violates the Standard prohibiting:",
    options:["Misrepresentation","Plagiarism","Priority of Transactions"], correctIndex:0,
    explanation:"Standard I(C) Misrepresentation prohibits any untrue statement, including guaranteeing returns on investments whose value is uncertain." },
  { id:"q-eth-6", volume:10, subject:"Ethical & Professional Standards", chapter:1, chapterTitle:"Ethics and Trust in the Investment Profession", difficulty:"easy",
    question:"When a conflict exists between the CFA Institute Code and Standards and less strict local law, a member should:",
    options:["follow the less strict local law","adhere to the stricter of the applicable law or the Code and Standards","disregard both and use personal judgment"], correctIndex:1,
    explanation:"Members must comply with the more strict of applicable law or the Code and Standards; the Standards govern when they impose a higher requirement than local law." },
  { id:"q-eth-7", volume:10, subject:"Ethical & Professional Standards", chapter:3, chapterTitle:"Guidance for Standards I-VII", difficulty:"medium",
    question:"Using a colleague's research report and presenting it as one's own without attribution is a violation of the Standard on:",
    options:["Misconduct","Misrepresentation (plagiarism)","Communication with Clients"], correctIndex:1,
    explanation:"Plagiarism—using others' work without acknowledgment—falls under Standard I(C) Misrepresentation, which prohibits copying or using material without proper attribution." },
  { id:"q-eth-8", volume:10, subject:"Ethical & Professional Standards", chapter:3, chapterTitle:"Guidance for Standards I-VII", difficulty:"hard",
    question:"In personal trading, a member should ensure that transactions for clients and the employer take priority over personal transactions, as required by the Standard on:",
    options:["Priority of Transactions","Preservation of Confidentiality","Referral Fees"], correctIndex:0,
    explanation:"Standard VI(B) Priority of Transactions requires that client and employer transactions take precedence over a member's personal trades." },
  { id:"q-eth-9", volume:10, subject:"Ethical & Professional Standards", chapter:4, chapterTitle:"Introduction to the Global Investment Performance Standards (GIPS)", difficulty:"medium",
    question:"The Global Investment Performance Standards (GIPS) are best described as a set of standards for:",
    options:["calculating and presenting investment performance fairly and with full disclosure","auditing a firm's financial statements","setting minimum capital requirements for firms"], correctIndex:0,
    explanation:"GIPS are voluntary, ethically grounded standards for the fair calculation and presentation of investment performance that promote comparability across firms." },
  { id:"q-eth-10", volume:10, subject:"Ethical & Professional Standards", chapter:3, chapterTitle:"Guidance for Standards I-VII", difficulty:"easy",
    question:"A member who keeps client information private and does not disclose it to third parties is complying with the Standard on:",
    options:["Preservation of Confidentiality","Additional Compensation Arrangements","Responsibilities of Supervisors"], correctIndex:0,
    explanation:"Standard III(E) Preservation of Confidentiality requires members to keep information about current, former, and prospective clients confidential unless disclosure is required by law or authorized by the client." },

];

// Expose for the app (used by Practice instead of the auto-generated bank).
if (typeof window !== 'undefined') { window.CURATED_QUESTIONS = CURATED_QUESTIONS; }
