#!/usr/bin/env python3
"""
CFA Level I - Quantitative Methods
Practice question bank (CFA-style MCQ) grounded in the 2025 Volume 1 curriculum.
Each entry: (question, [A, B, C], correct_index (0-based), explanation)
"""

QUESTION_BANK = {
"Module 1: Rates and Returns": [
("An interest rate is BEST described as having which three possible interpretations?",
 ["Required rate of return, discount rate, and opportunity cost",
  "Inflation premium, default premium, and liquidity premium",
  "Nominal rate, real rate, and risk-free rate"],
 0,
 "The curriculum states an interest rate r can be interpreted as (1) a required rate of return, (2) a discount rate, or (3) an opportunity cost."),

("An interest rate can be viewed as the sum of the real risk-free rate and a set of premiums. Which of the following is NOT one of those premiums?",
 ["Inflation premium", "Default risk premium", "Equity risk premium"],
 2,
 "The interest rate equals the real risk-free rate plus inflation, default, liquidity, and maturity premiums. The 'equity risk premium' is not part of this decomposition."),

("The nominal risk-free interest rate is BEST approximated as the sum of the:",
 ["real risk-free rate and the inflation premium",
  "real risk-free rate and the default risk premium",
  "real risk-free rate and the maturity premium"],
 0,
 "The nominal risk-free rate is approximated as the real risk-free rate plus the inflation premium."),

("An investor buys a stock for 50, receives a dividend of 2, and sells it for 54. The holding period return is closest to:",
 ["8.0%", "12.0%", "4.0%"],
 1,
 "HPR = (54 - 50 + 2)/50 = 6/50 = 12.0%. Total return = income yield + capital gain."),

("Which return measure is LEAST sensitive to the timing and amount of cash flows into and out of a portfolio?",
 ["Money-weighted return", "Time-weighted return", "Internal rate of return"],
 1,
 "The time-weighted return is not sensitive to the timing/amount of cash flows and is preferred for evaluating portfolio managers. The money-weighted return (an IRR) is sensitive to cash flow timing."),

("The time-weighted rate of return is generally the PREFERRED measure for evaluating portfolio managers because:",
 ["it accounts for the size of the investor's cash flows",
  "external cash flows are generally outside the manager's control",
  "it always exceeds the money-weighted return"],
 1,
 "Cash withdrawals/additions are generally outside the manager's control, so the time-weighted return - which removes their effect - is preferred for performance evaluation."),

("A money-weighted rate of return is BEST described as the:",
 ["compound growth rate of one unit of currency invested",
  "internal rate of return on a portfolio accounting for all cash flows",
  "simple average of subperiod returns"],
 1,
 "The money-weighted return is the IRR that reflects the actual return earned after accounting for the value and timing of all cash flows."),

("For a return series of +50% followed by -50%, the geometric mean return is closest to:",
 ["0%", "-13.4%", "+13.4%"],
 1,
 "Geometric mean = (1.50 x 0.50)^(1/2) - 1 = (0.75)^0.5 - 1 = -13.4%. The arithmetic mean would be 0%."),

("Relative to the arithmetic mean, the geometric mean return of a volatile, non-constant return series is:",
 ["always greater", "always less", "always equal"],
 1,
 "For any non-constant series, the geometric mean is always less than the arithmetic mean; they are equal only if all returns are identical."),

("Which mean is MOST appropriate for averaging ratios such as price-to-earnings multiples to reduce the impact of large outliers?",
 ["Harmonic mean", "Arithmetic mean", "Geometric mean"],
 0,
 "The harmonic mean is appropriate for averaging ratios/rates (e.g., cost averaging, P/E) and reduces the impact of large outliers."),

("A trimmed mean is BEST described as a mean computed after:",
 ["replacing the extreme values with the nearest retained values",
  "excluding a stated small percentage of the lowest and highest values",
  "weighting observations by their probability"],
 1,
 "A trimmed mean excludes a small stated percentage of the lowest and highest values. A winsorized mean replaces (not excludes) the extremes."),

("A winsorized mean differs from a trimmed mean in that the winsorized mean:",
 ["excludes the extreme observations entirely",
  "replaces the extreme observations with specified boundary values",
  "uses only the median observation"],
 1,
 "A winsorized mean replaces extreme values with specified boundary (percentile) values rather than excluding them."),

("A quarterly return of 3% compounded over four quarters produces an annualized return closest to:",
 ["12.00%", "12.55%", "11.45%"],
 1,
 "Annualized = (1.03)^4 - 1 = 1.1255 - 1 = 12.55%."),

("As the number of compounding periods per year approaches infinity, interest is said to be:",
 ["compounded continuously", "compounded discretely", "simple interest"],
 0,
 "With the number of compounding periods approaching infinity, interest is compounded continuously, using e^r."),

("If the holding period return over a stated period is 6%, the continuously compounded return for that period is closest to:",
 ["5.83%", "6.18%", "6.00%"],
 0,
 "Continuously compounded return = ln(1 + HPR) = ln(1.06) = 5.83%."),

("Gross return is BEST described as the return:",
 ["after deducting all managerial and administrative expenses",
  "prior to deduction of managerial and administrative expenses not directly related to return generation",
  "after deducting taxes on dividends and gains"],
 1,
 "Gross return is measured before deducting managerial/administrative expenses (those not directly related to generating returns) and is appropriate for comparing manager performance."),

("Net return is BEST described as:",
 ["gross return less managerial and administrative expenses",
  "gross return less only trading costs",
  "gross return plus the inflation premium"],
 0,
 "Net return = gross return less managerial and administrative expenses; it better reflects what the investor actually earned."),

("The after-tax nominal return is computed as the total return minus:",
 ["the inflation premium",
  "any allowance for taxes on dividends, interest, and realized gains",
  "managerial expenses only"],
 1,
 "After-tax nominal return = total return minus allowances for taxes on dividends, interest, and realized capital gains."),

("Real returns are PARTICULARLY useful for:",
 ["comparing returns across time periods when inflation rates vary",
  "evaluating a portfolio manager's stock selection skill",
  "measuring returns before any expenses"],
 0,
 "Real returns are useful for comparing returns across time periods (because inflation varies) and across asset classes with different taxation."),

("Leveraging a portfolio through borrowing or futures will MOST likely:",
 ["reduce both expected gains and losses",
  "amplify both the portfolio's gains and losses",
  "have no effect on the portfolio's risk"],
 1,
 "Leverage amplifies a portfolio's gains and losses."),
],

"Module 2: Time Value of Money in Finance": [
("The price of a coupon bond is BEST described as the sum of the present values of the bond's:",
 ["promised coupon payments and its par value",
  "par value only",
  "coupon payments only"],
 0,
 "A bond's price equals the present value of its promised coupons plus the present value of its par value."),

("For a pure discount (zero-coupon) bond, the price reflects the present value of:",
 ["the coupon payments only",
  "the par value only",
  "the coupons plus par value"],
 1,
 "Discount (zero-coupon) bonds have no coupons, so the price reflects only the present value of the par value."),

("According to the dividend discount model, the value of a stock should reflect the sum of the present values of:",
 ["the stock's expected future dividends in perpetuity",
  "the stock's expected future earnings",
  "the stock's book value plus next year's dividend"],
 0,
 "A stock's value should reflect the present value of its expected future dividends in perpetuity."),

("Stock valuation models based on dividends are typically classified by the assumed:",
 ["expected growth pattern of future dividends",
  "frequency of dividend payments",
  "industry of the issuer"],
 0,
 "Dividend-based valuation models are classified by the assumed dividend growth pattern: no growth, constant growth, or changing growth."),

("Using the constant-growth (Gordon) model, a stock with an expected dividend of 2.00, required return of 10%, and growth of 4% has a value closest to:",
 ["20.00", "33.33", "50.00"],
 1,
 "V = D1/(r - g) = 2.00/(0.10 - 0.04) = 2.00/0.06 = 33.33."),

("A no-growth (zero-growth) stock paying a constant dividend is valued as a:",
 ["perpetuity: D / r",
  "growing perpetuity: D1 / (r - g)",
  "finite annuity"],
 0,
 "With no growth, the stock is a level perpetuity valued at D/r."),

("Using the Gordon growth model, a stock's required return can be expressed as:",
 ["(D1 / P0) + g",
  "(D1 / P0) - g",
  "g - (D1 / P0)"],
 0,
 "Rearranging P0 = D1/(r - g) gives r = D1/P0 + g; the required return equals the dividend yield plus the growth rate."),

("A stock trades at 40, has an expected dividend of 1.60, and a required return of 9%. Its implied dividend growth rate is closest to:",
 ["5.0%", "4.0%", "9.0%"],
 0,
 "g = r - D1/P0 = 0.09 - 1.60/40 = 0.09 - 0.04 = 5.0%."),

("If a bond's price is known, the bond's implied return is BEST found by solving for the:",
 ["rate that equates the present value of cash flows to the price",
  "coupon rate divided by par value",
  "current yield only"],
 0,
 "The implied return (yield-to-maturity) is the discount rate that sets the present value of the bond's promised cash flows equal to its price."),

("The cash flow additivity principle allows two or more cash flow streams to be compared as long as the cash flows:",
 ["occur at the same point in time",
  "have the same nominal value",
  "are from the same issuer"],
 0,
 "Cash flow additivity applies when cash flows occur at the same point in time, allowing streams to be added/compared."),

("The cash flow additivity principle is MOST directly important because it ensures:",
 ["the no-arbitrage condition holds",
  "all bonds have equal yields",
  "inflation is properly accounted for"],
 0,
 "Cash flow additivity underpins no-arbitrage pricing: economically equivalent assets must have the same price."),

("Application of cash flow additivity confirms that asset prices are the same for:",
 ["economically equivalent assets, even with differing cash flow streams",
  "only assets with identical cash flow streams",
  "only assets from the same market"],
 0,
 "Cash flow additivity confirms economically equivalent assets have the same price even if their cash flow streams differ."),

("An implied forward interest rate is MOST directly derived using:",
 ["the cash flow additivity / no-arbitrage principle",
  "the dividend discount model",
  "the coefficient of variation"],
 0,
 "Implied forward rates are derived from spot rates using no-arbitrage (cash flow additivity) relationships."),

("The future value of a single cash flow under continuous compounding is given by:",
 ["FV = PV(1 + r)^t", "FV = PV x e^(rt)", "FV = PV / (1 + r)^t"],
 1,
 "Under continuous compounding, FV = PV x e^(rt)."),

("A 1,000 par, 5% annual coupon, 3-year bond priced when the market discount rate is 5% will trade at:",
 ["a premium to par", "par value (1,000)", "a discount to par"],
 1,
 "When the coupon rate equals the market discount rate, the bond prices at par."),

("All else equal, if the required return on a bond rises above its coupon rate, the bond will trade:",
 ["at a premium", "at a discount", "at par"],
 1,
 "When the required return exceeds the coupon rate, the present value of cash flows falls below par - the bond trades at a discount."),

("In the constant-growth dividend model, holding D1 and r constant, a higher growth rate g results in:",
 ["a higher stock value", "a lower stock value", "no change in value"],
 0,
 "A higher g reduces the denominator (r - g), increasing the stock's value, all else equal."),

("Cash flow additivity can be applied to value all of the following EXCEPT:",
 ["implied forward exchange rates",
  "option values via replicating portfolios",
  "the skewness of a return distribution"],
 2,
 "Cash flow additivity is used for forward rates, forward FX rates, and option values. Skewness is a statistical moment unrelated to no-arbitrage pricing."),

("A stock is valued using a two-stage (changing growth) dividend model when:",
 ["dividends are expected to grow at a high rate then settle to a stable rate",
  "the firm never pays dividends",
  "the discount rate is zero"],
 0,
 "A changing-growth (multi-stage) model is used when dividends grow at one rate initially and a different (often lower, stable) rate later."),

("The present value of a cash flow under continuous discounting is given by:",
 ["PV = FV x e^(-rt)", "PV = FV x e^(rt)", "PV = FV x (1 + r)^t"],
 0,
 "Under continuous discounting, PV = FV x e^(-rt)."),
],

"Module 3: Statistical Measures of Asset Returns": [
("Which measure of central tendency is MOST useful for skewed distributions because it is not influenced by extreme values?",
 ["Arithmetic mean", "Median", "Mode"],
 1,
 "The median is the middle value and is not influenced by extreme values, making it useful for skewed distributions."),

("The only measure of central tendency that can be used with nominal or categorical data is the:",
 ["mean", "median", "mode"],
 2,
 "The mode (most frequently observed value) is the only measure of central tendency usable with nominal/categorical data."),

("A distribution with two modes is described as:",
 ["unimodal", "bimodal", "trimodal"],
 1,
 "A distribution with two modes is bimodal."),

("Quartiles, quintiles, deciles, and percentiles are collectively known as:",
 ["measures of dispersion", "quantiles", "measures of skewness"],
 1,
 "These location parameters that divide a distribution into equal parts are collectively called quantiles."),

("In a box-and-whiskers plot, the 'box' depicts the:",
 ["interquartile range (Q3 - Q1)",
  "full range (max - min)",
  "standard deviation"],
 0,
 "The box represents the interquartile range - the difference between the third and first quartiles."),

("The range is considered to have limited usefulness as a dispersion measure because it:",
 ["uses information from only two observations",
  "cannot be computed for financial data",
  "is always negative"],
 0,
 "The range uses only the maximum and minimum values - just two observations - limiting its usefulness."),

("When computing a SAMPLE variance, the sum of squared deviations is divided by:",
 ["n", "n - 1", "n + 1"],
 1,
 "Sample variance uses a divisor of n - 1 (degrees of freedom) to provide an unbiased estimate."),

("The mean absolute deviation (MAD) for a sample is the average of the:",
 ["squared deviations of observations from the mean",
  "absolute deviations of observations from the mean",
  "deviations of observations from the median"],
 1,
 "The MAD is the average of the absolute deviations of observations from the mean."),

("A risk measure that focuses only on returns falling below a specified target is the:",
 ["coefficient of variation", "target downside deviation", "range"],
 1,
 "Target downside (semi)deviation measures the risk of outcomes below a given target return."),

("The coefficient of variation (CV) is BEST described as:",
 ["the standard deviation divided by the mean",
  "the mean divided by the standard deviation",
  "the variance minus the mean"],
 0,
 "CV = standard deviation / mean; it is a scale-free measure of relative dispersion."),

("A key advantage of the coefficient of variation is that it:",
 ["has units of currency",
  "is a scale-free measure allowing direct comparison across datasets",
  "ignores the mean entirely"],
 1,
 "By dividing dispersion by the mean, CV becomes scale-free (no units), enabling direct comparisons across datasets."),

("Two portfolios have equal standard deviations, but Portfolio A has a higher mean return. Comparing coefficients of variation, Portfolio A has:",
 ["a lower CV (less risk per unit of return)",
  "a higher CV",
  "the same CV"],
 0,
 "CV = SD/mean. With equal SD and a higher mean, Portfolio A has a lower CV, i.e., less risk per unit of return."),

("An asset return distribution with frequent small losses and a few extreme gains relative to a normal distribution exhibits:",
 ["positive skewness", "negative skewness", "zero skewness"],
 0,
 "Positive (right) skewness: frequent small losses and a few extreme gains; the long tail is on the right."),

("A return distribution with frequent small gains and a few extreme losses is BEST described as:",
 ["positively skewed", "negatively skewed", "symmetric"],
 1,
 "Negative (left) skewness: frequent small gains and a few extreme losses; the long tail is on the left."),

("The kurtosis of a normal distribution is:",
 ["0", "1", "3"],
 2,
 "The kurtosis of a normal distribution is 3; excess kurtosis (kurtosis - 3) is therefore 0."),

("A distribution with fatter tails than the normal distribution is described as:",
 ["leptokurtic (fat-tailed)", "platykurtic (thin-tailed)", "mesokurtic"],
 0,
 "A fat-tailed distribution is leptokurtic; a thin-tailed distribution is platykurtic."),

("Excess kurtosis greater than zero indicates a distribution that is:",
 ["thin-tailed relative to normal",
  "fat-tailed relative to normal",
  "identical to the normal distribution"],
 1,
 "Positive excess kurtosis (kurtosis > 3) indicates fatter tails than the normal distribution (leptokurtic)."),

("For investment returns, a leptokurtic (fat-tailed) distribution implies that extreme outcomes are:",
 ["less likely than under a normal distribution",
  "more likely than under a normal distribution",
  "equally likely as under a normal distribution"],
 1,
 "Fat tails (leptokurtosis) mean extreme outcomes occur more frequently than a normal distribution would predict - an important risk consideration."),

("The correlation coefficient between two variables ranges between:",
 ["0 and +1", "-1 and +1", "-infinity and +infinity"],
 1,
 "Correlation, a standardized measure of linear association, ranges from -1 to +1."),

("A correlation coefficient close to zero between two asset returns indicates:",
 ["a strong positive linear relationship",
  "little or no linear relationship",
  "a strong negative linear relationship"],
 1,
 "A correlation near zero indicates little or no linear relationship between the two variables."),
],

"Module 4: Probability Trees and Conditional Expectations": [
("The expected value of a random variable X is BEST described as the:",
 ["probability-weighted average of the possible outcomes",
  "simple average of the possible outcomes",
  "most likely single outcome"],
 0,
 "E(X) is the probability-weighted average of the random variable's possible outcomes."),

("The variance of a random variable X is defined as:",
 ["E[X - E(X)]", "E{[X - E(X)]^2}", "the square root of E(X)"],
 1,
 "Variance is the probability-weighted average of squared deviations from the mean: sigma^2(X) = E{[X - E(X)]^2}."),

("A stock has a 60% probability of a 10% return and a 40% probability of a -5% return. Its expected return is closest to:",
 ["4.0%", "2.5%", "7.0%"],
 0,
 "E(R) = 0.60(10%) + 0.40(-5%) = 6% - 2% = 4.0%."),

("Standard deviation is preferred to variance for interpreting dispersion because it is:",
 ["always smaller than the variance",
  "measured in the same units as the variable",
  "unaffected by outliers"],
 1,
 "Standard deviation is the positive square root of variance and is expressed in the same units as the variable, aiding interpretation."),

("A probability tree is BEST described as a means of illustrating:",
 ["the results of two or more events and their probabilities",
  "a single deterministic outcome",
  "the correlation between two variables"],
 0,
 "A probability tree visually illustrates the outcomes of two or more events along with conditional and joint probabilities."),

("The conditional probability of event A given event B, P(A|B), is defined as:",
 ["P(AB) / P(B), with P(B) not equal to 0",
  "P(A) x P(B)",
  "P(A) + P(B) - P(AB)"],
 0,
 "By definition, P(A|B) = P(AB)/P(B), provided P(B) is not zero."),

("Two events A and B are independent if and only if:",
 ["P(A|B) = P(A)",
  "P(A|B) = P(B)",
  "P(AB) = P(A) + P(B)"],
 0,
 "Independence means the occurrence of B does not change the probability of A: P(A|B) = P(A), equivalently P(AB) = P(A)P(B)."),

("According to the total probability rule, if S1, S2, ..., Sn are mutually exclusive and exhaustive, then P(A) equals:",
 ["the sum of P(A | Si) x P(Si) across all scenarios",
  "the product of all P(Si)",
  "P(A | S1) only"],
 0,
 "The total probability rule: P(A) = sum over i of P(A|Si)P(Si) for mutually exclusive and exhaustive scenarios."),

("Bayes' formula is BEST described as a method to:",
 ["update prior probabilities based on new information",
  "compute the variance of a portfolio",
  "rank data without distributional assumptions"],
 0,
 "Bayes' formula provides a rational method to update (revise) prior probabilities as new information arrives."),

("In Bayes' formula, the updated probability equals the prior probability multiplied by the ratio of:",
 ["probability of the new information given the event to the unconditional probability of the new information",
  "the unconditional probability of the event to the conditional probability",
  "the variance to the mean"],
 0,
 "Updated probability = [P(information|event)/P(information)] x prior probability of the event."),

("Conditional expected value E(X|S) is calculated as the probability-weighted average of outcomes:",
 ["using conditional probabilities given scenario S",
  "ignoring scenario S entirely",
  "using only the largest outcome"],
 0,
 "E(X|S) = sum of P(Xi|S) x Xi - a probability-weighted average using conditional probabilities given S."),

("A 'mutually exclusive and exhaustive' set of scenarios means the scenarios:",
 ["cannot occur together and cover all possibilities",
  "can occur together and overlap",
  "exclude some possible outcomes"],
 0,
 "Mutually exclusive = cannot occur simultaneously; exhaustive = together cover all possible outcomes."),

("The expected value of a constant a times a random variable X, E(aX), equals:",
 ["a x E(X)", "a + E(X)", "E(X) / a"],
 0,
 "Expectation is a linear operator: E(aX) = a x E(X)."),

("A portfolio analyst assigns a 30% probability to a recession. Conditional on recession, a stock returns -8%; otherwise it returns +12%. The expected return is closest to:",
 ["+6.0%", "+12.0%", "-8.0%"],
 0,
 "E(R) = 0.30(-8%) + 0.70(12%) = -2.4% + 8.4% = 6.0%."),

("Bayes' formula is MOST useful in investment settings for:",
 ["revising the probability of a state given a new signal or observation",
  "computing a bond's yield-to-maturity",
  "measuring the kurtosis of returns"],
 0,
 "Bayes' formula updates the probability of an underlying state given a newly observed signal (e.g., an earnings surprise)."),

("If two events are mutually exclusive, then P(A and B) equals:",
 ["0", "P(A) x P(B)", "P(A) + P(B)"],
 0,
 "Mutually exclusive events cannot occur together, so their joint probability P(A and B) = 0."),

("The variance of a random variable can be computed using a probability tree by:",
 ["probability-weighting the squared deviations of each terminal outcome from E(X)",
  "summing all terminal outcomes",
  "averaging the probabilities"],
 0,
 "Variance = probability-weighted sum of squared deviations of each outcome from the expected value E(X)."),

("Given P(B) = 0.5 and P(AB) = 0.2, the conditional probability P(A|B) is:",
 ["0.40", "0.10", "0.70"],
 0,
 "P(A|B) = P(AB)/P(B) = 0.2/0.5 = 0.40."),

("In Bayes' formula, the denominator (unconditional probability of the new information) is typically computed using the:",
 ["total probability rule", "harmonic mean", "central limit theorem"],
 0,
 "The unconditional probability of the information is found via the total probability rule across all states."),

("The standard deviation of a random variable is always:",
 ["non-negative", "negative for risky assets", "equal to the variance"],
 0,
 "Standard deviation is the positive square root of variance and is therefore always non-negative."),
],

"Module 5: Portfolio Mathematics": [
("The expected return of a portfolio is BEST described as:",
 ["a weighted average of the expected returns on the component securities",
  "the simple sum of the component security returns",
  "the geometric mean of component returns"],
 0,
 "E(Rp) is the weighted average of the component securities' expected returns, using portfolio weights."),

("A portfolio invests 60% in Asset A (expected return 8%) and 40% in Asset B (expected return 12%). The portfolio expected return is:",
 ["9.6%", "10.0%", "20.0%"],
 0,
 "E(Rp) = 0.60(8%) + 0.40(12%) = 4.8% + 4.8% = 9.6%."),

("Portfolio variance depends on the risk of individual assets and their:",
 ["covariances", "expected returns only", "weights only"],
 0,
 "Portfolio variance reflects individual asset variances and the covariances (co-movement) between asset returns."),

("The covariance between the returns of two assets can be:",
 ["only positive",
  "negative, zero, or positive",
  "only between -1 and +1"],
 1,
 "Covariance can be negative (inverse relationship), zero (unrelated), or positive (direct relationship). Correlation, by contrast, is bounded by -1 and +1."),

("For a two-asset portfolio, the variance is given by w1^2 sigma1^2 + w2^2 sigma2^2 plus:",
 ["2 w1 w2 Cov(R1, R2)",
  "w1 w2 (sigma1 + sigma2)",
  "Cov(R1, R2) / (w1 w2)"],
 0,
 "Two-asset portfolio variance = w1^2 sigma1^2 + w2^2 sigma2^2 + 2 w1 w2 Cov(R1,R2)."),

("The correlation coefficient between two assets is computed as the covariance divided by:",
 ["the product of the two standard deviations",
  "the sum of the two variances",
  "the portfolio mean"],
 0,
 "Correlation = Cov(Ri,Rj) / (sigma_i x sigma_j)."),

("Diversification benefits in a two-asset portfolio are GREATEST when the correlation between the assets is:",
 ["+1", "0", "-1"],
 2,
 "The lower the correlation, the greater the diversification benefit; a correlation of -1 offers the maximum risk reduction."),

("If two assets have a correlation of +1, the portfolio standard deviation is:",
 ["the weighted average of the two standard deviations",
  "always zero",
  "always greater than either asset's standard deviation"],
 0,
 "With perfect positive correlation, no diversification benefit exists, and the portfolio SD equals the weighted average of the component SDs."),

("Two random variables X and Y are independent if and only if their joint probability function satisfies:",
 ["P(X,Y) = P(X)P(Y)",
  "P(X,Y) = P(X) + P(Y)",
  "P(X,Y) = P(X)/P(Y)"],
 0,
 "Independence requires P(X,Y) = P(X)P(Y) for all values."),

("For two independent (and therefore uncorrelated) random variables, the expected value of their product equals:",
 ["the product of their expected values",
  "the sum of their expected values",
  "zero"],
 0,
 "For independent variables, E(XY) = E(X)E(Y)."),

("Shortfall risk is BEST defined as the:",
 ["probability that a portfolio's value will fall below a minimum acceptable level",
  "maximum possible loss on a portfolio",
  "variance of portfolio returns"],
 0,
 "Shortfall risk is the probability that the portfolio return/value falls below a specified minimum (threshold) level."),

("Roy's safety-first criterion selects the portfolio that:",
 ["maximizes the safety-first ratio (SFRatio)",
  "minimizes the expected return",
  "maximizes the variance"],
 0,
 "Roy's safety-first criterion chooses the portfolio with the highest safety-first ratio, minimizing the probability of returns below the threshold."),

("The safety-first ratio (SFRatio) is computed as:",
 ["[E(Rp) - RL] / sigma_p",
  "[E(Rp) + RL] / sigma_p",
  "sigma_p / [E(Rp) - RL]"],
 0,
 "SFRatio = [E(Rp) - RL] / sigma_p, where RL is the threshold (minimum acceptable) return."),

("Portfolio P has E(R) = 10%, threshold return 2%, and SD = 16%. Its safety-first ratio is:",
 ["0.50", "0.75", "0.625"],
 0,
 "SFRatio = (10% - 2%)/16% = 8/16 = 0.50."),

("Assuming returns are normally distributed, the optimal safety-first portfolio also minimizes the:",
 ["probability of returns below the threshold level",
  "portfolio expected return",
  "number of assets held"],
 0,
 "A higher SFRatio corresponds to a lower probability of returns falling below the threshold (under normality)."),

("Covariance of an asset's return with itself equals the asset's:",
 ["variance", "standard deviation", "expected return"],
 0,
 "Cov(R, R) = Var(R); an asset's covariance with itself is its own variance."),

("Adding an asset with low or negative correlation to a portfolio will MOST likely:",
 ["reduce the portfolio's overall risk",
  "increase the portfolio's overall risk",
  "leave portfolio risk unchanged"],
 0,
 "Low or negative correlation enhances diversification, reducing overall portfolio risk."),

("Using a joint probability function, the covariance of returns RA and RB is computed by summing, over all outcomes:",
 ["P(RA,i, RB,j) x (RA,i - E[RA]) x (RB,j - E[RB])",
  "P(RA,i) x P(RB,j)",
  "(RA,i - RB,j)^2"],
 0,
 "Cov(RA,RB) = sum over i,j of P(RA,i,RB,j)(RA,i - E[RA])(RB,j - E[RB]) - probability-weighted cross products of deviations."),

("If the safety-first ratios of three portfolios are 0.40, 0.55, and 0.50, an investor following Roy's criterion should choose the portfolio with SFRatio:",
 ["0.55", "0.50", "0.40"],
 0,
 "Roy's safety-first criterion selects the portfolio with the highest SFRatio - here, 0.55."),

("A portfolio's expected return calculation requires which inputs?",
 ["The expected returns of the assets and their portfolio weights",
  "Only the covariances of the assets",
  "Only the variances of the assets"],
 0,
 "Portfolio expected return is the weighted average of component expected returns, requiring the assets' expected returns and weights."),
],

"Module 6: Simulation Methods": [
("A random variable Y follows a lognormal distribution if:",
 ["the natural logarithm of Y is normally distributed",
  "Y is normally distributed",
  "Y is uniformly distributed"],
 0,
 "Y is lognormal if ln(Y) is normally distributed ('the log is normal')."),

("The lognormal distribution is widely used to model asset PRICES primarily because it is:",
 ["bounded below by zero and skewed to the right",
  "symmetric and can be negative",
  "always thin-tailed"],
 0,
 "Asset prices cannot be negative; the lognormal distribution is bounded below by 0 and is right-skewed, matching price behavior."),

("The lognormal distribution is typically:",
 ["skewed to the right (long right tail)",
  "skewed to the left",
  "perfectly symmetric"],
 0,
 "The lognormal distribution is skewed to the right with a long right tail."),

("Which distribution is often a good approximation for asset RETURNS (as opposed to prices)?",
 ["The normal distribution",
  "The lognormal distribution",
  "The chi-square distribution"],
 0,
 "The normal distribution is often a good approximation for returns, while the lognormal is used for prices."),

("Continuously compounded returns play a key role in many asset pricing models and are MOST naturally linked to which distribution of prices?",
 ["Lognormal", "Uniform", "Binomial"],
 0,
 "If continuously compounded returns are normally distributed, prices are lognormally distributed."),

("Monte Carlo simulation is MOST commonly used to:",
 ["value securities with complex features where no analytic pricing formula exists",
  "compute a simple arithmetic mean",
  "rank categorical data"],
 0,
 "Monte Carlo simulation is used to estimate risk/return and value complex securities (e.g., with embedded options) lacking closed-form solutions."),

("A Monte Carlo simulation works by:",
 ["generating a large number of random samples from specified probability distributions",
  "using only historical average returns",
  "solving a single deterministic equation"],
 0,
 "Monte Carlo generates many random samples from specified distribution(s) to obtain the likelihood of a range of outcomes."),

("A key limitation of Monte Carlo simulation is that:",
 ["its results are only as good as the assumptions and distributions specified",
  "it can only be used for bonds",
  "it requires no input assumptions"],
 0,
 "Monte Carlo output depends entirely on the input assumptions/distributions chosen ('garbage in, garbage out')."),

("Bootstrap resampling constructs a sampling distribution by:",
 ["repeatedly drawing samples from the observed sample, treating it as the population",
  "drawing samples from a theoretical normal distribution only",
  "using a single draw from the population"],
 0,
 "Bootstrapping treats the observed sample as if it were the population and repeatedly resamples from it."),

("Bootstrapping is justified by the idea that:",
 ["a random sample offers a good representation of the population",
  "the population is always normally distributed",
  "sample size does not matter"],
 0,
 "Because a random sample represents the population well, resampling from it mimics sampling from the population."),

("A primary difference between Monte Carlo simulation and bootstrapping is that bootstrapping:",
 ["resamples from observed historical data rather than a specified theoretical distribution",
  "never uses random sampling",
  "cannot be used for standard errors"],
 0,
 "Bootstrapping draws from observed data; Monte Carlo draws from specified theoretical distributions."),

("Monte Carlo simulation is BEST described as a complement to, rather than a replacement for, which type of analysis?",
 ["Analytical (closed-form) methods",
  "Categorical data analysis",
  "Ranking methods"],
 0,
 "Monte Carlo complements analytical methods, providing estimates where closed-form (analytical) solutions are unavailable."),

("In a Monte Carlo simulation of an option, repeatedly simulating the underlying asset's price path allows estimation of the option's:",
 ["expected payoff and hence its value",
  "exact historical return",
  "credit rating"],
 0,
 "Simulating many price paths yields a distribution of payoffs whose average (discounted) approximates the option's value."),

("Bootstrapping can be applied in finance for all of the following EXCEPT:",
 ["estimating the standard error of a sample mean",
  "historical simulation in asset allocation",
  "guaranteeing future investment returns"],
 2,
 "Bootstrapping estimates sampling distributions (e.g., standard errors) and supports historical simulation, but cannot guarantee future returns."),

("If continuously compounded returns are normal with mean mu and variance sigma^2, the corresponding price distribution is lognormal because prices equal:",
 ["the initial price times e raised to the return",
  "the initial price plus the return",
  "the return divided by the initial price"],
 0,
 "Price = P0 x e^(return); exponentiating a normal return produces a lognormal price."),

("A Monte Carlo simulation that produces a wide range of possible outcomes is MOST useful for:",
 ["assessing the risk and distribution of potential results",
  "finding a single guaranteed outcome",
  "eliminating all uncertainty"],
 0,
 "Monte Carlo characterizes the distribution and risk of outcomes rather than producing a single certain answer."),

("The lognormal distribution appears in which well-known option pricing model?",
 ["Black-Scholes-Merton", "Gordon growth model", "Capital asset pricing model"],
 0,
 "The Black-Scholes-Merton model assumes the underlying asset price is lognormally distributed."),

("Compared with the normal distribution, the lognormal distribution CANNOT take:",
 ["negative values", "values above one", "fractional values"],
 0,
 "The lognormal distribution is bounded below by zero, so it cannot take negative values - suitable for asset prices."),

("Which step is essential when designing a Monte Carlo simulation?",
 ["Specifying the probability distribution(s) for the risk factors",
  "Assuming all variables are constant",
  "Using only one random draw"],
 0,
 "A Monte Carlo simulation requires specifying the probability distribution(s) of the underlying risk factors before generating random samples."),

("Bootstrap resampling typically draws samples that are:",
 ["the same size as the original observed sample",
  "always larger than the population",
  "always a single observation"],
 0,
 "Bootstrap repeatedly draws samples of the same size as the original sample (with replacement)."),
],

"Module 7: Estimation and Inference": [
("Which of the following is a PROBABILITY sampling method?",
 ["Simple random sampling", "Convenience sampling", "Judgmental sampling"],
 0,
 "Probability sampling includes simple random and stratified random sampling. Convenience and judgmental sampling are non-probability methods."),

("Stratified random sampling involves:",
 ["dividing the population into subgroups and randomly sampling from each",
  "selecting whichever observations are easiest to obtain",
  "relying on the researcher's expert judgment"],
 0,
 "Stratified random sampling divides the population into strata and draws random samples from each subgroup."),

("Sampling error is BEST defined as the difference between:",
 ["a sample statistic and the population parameter it estimates",
  "two different population parameters",
  "the mean and the median of a sample"],
 0,
 "Sampling error is the difference between the observed value of a statistic and the parameter it is intended to estimate."),

("A key advantage of non-probability sampling methods is that they:",
 ["allow quick and low-cost data collection",
  "guarantee a representative sample",
  "eliminate sampling error"],
 0,
 "Non-probability methods are quick and low-cost and can apply expert judgment, but carry a significant risk of being non-representative."),

("A major risk of non-probability sampling is that the sample may be:",
 ["non-representative of the population",
  "too large to analyze",
  "free of any bias"],
 0,
 "Non-probability sampling does not give every population member an equal chance of selection, risking a non-representative sample."),

("The central limit theorem states that, for large sample size n, the sampling distribution of the sample mean is approximately:",
 ["normal with mean mu and variance sigma^2/n",
  "lognormal with mean mu",
  "uniform regardless of n"],
 0,
 "The CLT: for large n, the sample mean is approximately normal with mean mu and variance sigma^2/n, regardless of the population distribution."),

("A powerful implication of the central limit theorem is that it holds:",
 ["regardless of the shape of the underlying population distribution",
  "only when the population is normal",
  "only for binomial populations"],
 0,
 "The CLT applies to any population distribution with finite variance, provided the sample size is large."),

("The standard error of the sample mean equals the population standard deviation divided by:",
 ["the square root of n", "n", "n squared"],
 0,
 "Standard error of the mean = sigma / sqrt(n) (estimated using s/sqrt(n) when sigma is unknown)."),

("If a population has a standard deviation of 20 and the sample size is 100, the standard error of the sample mean is:",
 ["2.0", "0.2", "20.0"],
 0,
 "SE = sigma/sqrt(n) = 20/sqrt(100) = 20/10 = 2.0."),

("All else equal, increasing the sample size n will cause the standard error of the sample mean to:",
 ["decrease", "increase", "remain unchanged"],
 0,
 "Because SE = sigma/sqrt(n), a larger n reduces the standard error, improving the precision of the estimate."),

("According to the central limit theorem, the mean of the sampling distribution of the sample mean equals the:",
 ["population mean", "sample standard deviation", "median of the sample"],
 0,
 "The CLT establishes that the mean of the sampling distribution of the sample mean equals the population mean mu."),

("Resampling methods such as the bootstrap and jackknife are used to:",
 ["estimate the sampling distribution of a statistic",
  "eliminate the need for any data",
  "compute the population parameter exactly"],
 0,
 "Bootstrap and jackknife are resampling methods used to estimate the sampling distribution (e.g., standard error) of a statistic."),

("The bootstrap differs from a purely analytical approach to the standard error in that it:",
 ["uses computer simulation rather than an analytical formula such as a z- or t-statistic",
  "requires the population variance to be known",
  "can only be used for the mean"],
 0,
 "The bootstrap uses computer-based resampling instead of an analytical formula, and works for complicated estimators."),

("A potential advantage of the bootstrap over analytical formulas is its:",
 ["accuracy and wide applicability to complicated estimators",
  "requirement of fewer than ten observations",
  "guarantee of zero sampling error"],
 0,
 "The bootstrap can offer accuracy advantages and applies widely (e.g., asset allocation simulations, benchmark comparisons)."),

("Which sampling method selects observations based purely on ease of access?",
 ["Convenience sampling", "Stratified random sampling", "Simple random sampling"],
 0,
 "Convenience sampling selects observations that are easiest to obtain - a non-probability method."),

("In simple random sampling, each member of the population has:",
 ["an equal chance of being selected",
  "a chance proportional to its value",
  "no chance of being selected twice"],
 0,
 "Simple random sampling gives every population member an equal probability of selection."),

("The standard error is important because it measures the:",
 ["precision (variability) of the sample mean as an estimate of the population mean",
  "skewness of the population",
  "kurtosis of the sample"],
 0,
 "The standard error quantifies how much the sample mean is expected to vary from the population mean - i.e., the estimate's precision."),

("As the number of compounding subsamples grows, bootstrapping is MOST appropriately described as:",
 ["repeatedly drawing samples of the same size from the original sample",
  "drawing one large sample from the population",
  "computing a deterministic formula"],
 0,
 "Bootstrapping repeatedly draws samples of the same size as the original (with replacement) to build a sampling distribution."),

("Judgmental sampling relies primarily on:",
 ["the researcher's expertise to select the sample",
  "a random number generator",
  "stratifying the population"],
 0,
 "Judgmental sampling uses the researcher's expert judgment to select sample members - a non-probability method."),

("A larger sample size is generally desirable in estimation because it tends to:",
 ["reduce sampling error and increase estimate precision",
  "increase the standard error",
  "guarantee the sample is biased"],
 0,
 "Larger samples generally reduce sampling error and produce more precise estimates of population parameters."),
],

"Module 8: Hypothesis Testing": [
("Which of the following is the FIRST step in hypothesis testing?",
 ["State the hypotheses",
  "Calculate the test statistic",
  "Make a decision"],
 0,
 "The steps begin with (1) stating the hypotheses, then identifying the test statistic, specifying significance, stating the decision rule, computing, and deciding."),

("A Type I error occurs when an analyst:",
 ["rejects a true null hypothesis",
  "fails to reject a false null hypothesis",
  "accepts the alternative when it is true"],
 0,
 "A Type I error (false positive) is rejecting a null hypothesis that is actually true."),

("A Type II error occurs when an analyst:",
 ["fails to reject a false null hypothesis",
  "rejects a true null hypothesis",
  "correctly rejects a false null"],
 0,
 "A Type II error (false negative) is failing to reject a null hypothesis that is actually false."),

("The level of significance of a test is the probability of:",
 ["a Type I error", "a Type II error", "a correct decision"],
 0,
 "The significance level (alpha) is the probability of committing a Type I error."),

("The power of a test is BEST defined as:",
 ["the probability of correctly rejecting a false null hypothesis",
  "the probability of a Type I error",
  "the probability of a Type II error"],
 0,
 "Power = 1 - P(Type II error); it is the probability of correctly rejecting a false null hypothesis."),

("The confidence level of a test is the complement of the:",
 ["level of significance",
  "power of the test",
  "probability of a Type II error"],
 0,
 "Confidence level = 1 - significance level (alpha)."),

("For a test of the population mean of a normally distributed population with UNKNOWN variance, the theoretically correct test statistic is the:",
 ["t-statistic", "z-statistic", "chi-square statistic"],
 0,
 "When the population variance is unknown, the t-statistic is theoretically correct for testing the population mean."),

("A test statistic is BEST described as a quantity, calculated from a sample, that is:",
 ["the basis for deciding whether to reject the null hypothesis",
  "always equal to the population parameter",
  "the probability of the null being true"],
 0,
 "The test statistic is computed from the sample and compared to a critical value to decide whether to reject the null."),

("To test whether the difference between two means from independent samples (normal populations, unknown but equal variances) is significant, the appropriate test is a:",
 ["t-test based on pooling the two samples' observations",
  "chi-square test",
  "paired comparisons test"],
 0,
 "For independent samples from normal populations with unknown but equal variances, a pooled-variance t-test is used."),

("When two samples are dependent (e.g., before-and-after observations on the same subjects), the appropriate test is a:",
 ["paired comparisons (mean differences) test",
  "pooled-variance t-test for independent samples",
  "F-test of variances"],
 0,
 "Dependent (related) samples call for a paired comparisons test (a test of mean differences)."),

("For a test concerning the variance of a SINGLE normally distributed population, the appropriate test statistic is:",
 ["chi-square with n - 1 degrees of freedom",
  "an F-statistic",
  "a z-statistic"],
 0,
 "A test of a single population variance uses a chi-square statistic with n - 1 degrees of freedom."),

("For a test of the EQUALITY of variances of two normally distributed populations from independent samples, the appropriate test statistic is:",
 ["an F-statistic (ratio of sample variances)",
  "a chi-square statistic",
  "a t-statistic"],
 0,
 "Comparing two population variances uses an F-test - the ratio of the two sample variances."),

("The degrees of freedom for the F-test comparing two sample variances are:",
 ["n1 - 1 and n2 - 1",
  "n1 + n2 - 2",
  "n - 1"],
 0,
 "The F-test uses two degrees-of-freedom parameters: n1 - 1 (numerator) and n2 - 1 (denominator)."),

("A parametric test is BEST described as a test that:",
 ["concerns a population parameter or relies on specific distributional assumptions",
  "makes no distributional assumptions",
  "can only be used on ranked data"],
 0,
 "Parametric tests concern a parameter and/or rely on specific distributional assumptions."),

("If the calculated test statistic exceeds the critical value (in absolute terms for a two-sided test), the analyst should:",
 ["reject the null hypothesis",
  "fail to reject the null hypothesis",
  "increase the significance level"],
 0,
 "When the test statistic falls in the rejection region (beyond the critical value), the null hypothesis is rejected."),

("Decreasing the significance level (alpha) from 0.05 to 0.01, holding all else constant, will:",
 ["decrease the probability of a Type I error but increase the probability of a Type II error",
  "decrease both Type I and Type II error probabilities",
  "increase the probability of a Type I error"],
 0,
 "Lowering alpha reduces Type I error probability but, all else equal, raises the probability of a Type II error."),

("A p-value is BEST described as the:",
 ["smallest significance level at which the null hypothesis can be rejected",
  "probability that the null hypothesis is true",
  "probability of a Type II error"],
 0,
 "The p-value is the smallest level of significance at which the null can be rejected; reject if p-value < alpha."),

("A one-sided (one-tailed) alternative hypothesis is appropriate when the analyst:",
 ["is testing for a difference in a specific direction",
  "is testing only for any difference, regardless of direction",
  "has no prior expectation"],
 0,
 "A one-sided test is used when the hypothesis specifies a direction (greater than or less than)."),

("In hypothesis testing, the null hypothesis typically represents the:",
 ["statement to be tested, often 'no effect' or 'no difference'",
  "outcome the researcher hopes to prove",
  "alternative under consideration"],
 0,
 "The null hypothesis is the statement to be tested (often 'no effect'); the alternative is what is concluded if the null is rejected."),

("For a fixed sample size, increasing the power of a test generally requires:",
 ["accepting a higher probability of a Type I error",
  "reducing the significance level",
  "no trade-off whatsoever"],
 0,
 "For a fixed sample size, there is a trade-off: increasing power (reducing Type II error) generally requires accepting a higher Type I error probability (higher alpha)."),
],

"Module 9: Parametric and Non-Parametric Tests of Independence": [
("A two-sided alternative hypothesis concerning a parameter theta is BEST written as:",
 ["H0: theta = theta0 versus Ha: theta not equal to theta0",
  "H0: theta <= theta0 versus Ha: theta > theta0",
  "H0: theta >= theta0 versus Ha: theta < theta0"],
 0,
 "A two-sided test: H0: theta = theta0 versus Ha: theta is not equal to theta0."),

("A nonparametric test is MOST appropriate when:",
 ["data do not meet distributional assumptions or are given in ranks",
  "the population is known to be normal",
  "a population parameter is the sole focus and assumptions hold"],
 0,
 "Nonparametric tests are used when distributional assumptions are not met, outliers exist, data are ranks, or the hypothesis does not concern a parameter."),

("To test whether a population correlation coefficient differs from zero, the test statistic follows a t-distribution with degrees of freedom equal to:",
 ["n - 2", "n - 1", "n"],
 0,
 "The t-test for a correlation coefficient has n - 2 degrees of freedom."),

("The null hypothesis for the most common two-sided test of correlation is:",
 ["H0: rho = 0", "H0: rho = 1", "H0: rho < 0"],
 0,
 "The common test asks whether any relationship exists, testing H0: rho = 0 (no correlation)."),

("The Spearman rank correlation coefficient is calculated using the:",
 ["ranks of the two variables within their samples",
  "raw values of the two variables",
  "squared values of the variables"],
 0,
 "The Spearman rank correlation is computed on the ranks of the two variables, not their raw values."),

("The Spearman rank correlation is MOST useful when:",
 ["data do not meet the assumptions required for the parametric correlation test",
  "the data are perfectly normally distributed",
  "the sample size exceeds one million"],
 0,
 "Spearman rank correlation (nonparametric) is useful when parametric assumptions (e.g., normality) are not met or with ranked/outlier-prone data."),

("A test of independence between two categorical variables uses which test statistic?",
 ["Chi-square", "t-statistic", "F-statistic"],
 0,
 "A chi-square test statistic is used to test the independence of two categorical variables using a contingency table."),

("A test of independence using a contingency table compares actual frequencies with the frequencies expected under:",
 ["the assumption of independence",
  "perfect positive correlation",
  "a normal distribution"],
 0,
 "The chi-square test of independence compares observed frequencies to those expected if the two variables were independent."),

("A contingency table is BEST described as a table that:",
 ["displays the joint frequencies of two categorical variables",
  "lists the present values of cash flows",
  "ranks observations from smallest to largest"],
 0,
 "A contingency table presents the joint frequencies (counts) of observations across categories of two variables."),

("For a chi-square test of independence with r rows and c columns, the expected frequency in a cell equals:",
 ["(row total x column total) / grand total",
  "row total x column total",
  "(row total + column total) / 2"],
 0,
 "Expected cell frequency = (row total x column total)/grand total under the independence assumption."),

("A nonparametric test is characterized by the fact that it:",
 ["makes minimal assumptions about the population distribution",
  "always requires a normal population",
  "can only test the population mean"],
 0,
 "Nonparametric tests make minimal (or no) assumptions about the underlying population distribution."),

("A parametric test, in contrast to a nonparametric test, is one that:",
 ["concerns a parameter or relies on specific distributional assumptions",
  "ignores the population distribution",
  "can only use ranked data"],
 0,
 "Parametric tests concern a population parameter and/or assume a specific distribution; nonparametric tests do not."),

("If the calculated chi-square statistic in a test of independence exceeds the critical value, the analyst concludes that the two variables are:",
 ["not independent (i.e., related)",
  "independent",
  "perfectly correlated"],
 0,
 "Rejecting the null (chi-square > critical) indicates the variables are not independent - there is a relationship."),

("Which situation MOST strongly favors a nonparametric over a parametric test?",
 ["The presence of significant outliers in small samples",
  "A large sample drawn from a normal population",
  "A test concerning a single normal mean with known variance"],
 0,
 "Nonparametric tests are preferred with outliers, ranked data, small samples, or when distributional assumptions are violated."),

("A right-side one-sided test of correlation has the alternative hypothesis:",
 ["Ha: rho > 0", "Ha: rho < 0", "Ha: rho not equal to 0"],
 0,
 "A right-side (one-sided) test: H0: rho <= 0 versus Ha: rho > 0."),

("The t-statistic for testing a correlation coefficient increases (in absolute value), all else equal, as the sample size n:",
 ["increases", "decreases", "stays the same"],
 0,
 "A larger n increases the t-statistic for correlation (the formula multiplies r by sqrt[(n-2)/(1-r^2)]), making significance easier to detect."),

("A contingency-table chi-square test statistic is computed by summing, across all cells, the quantity:",
 ["(observed - expected)^2 / expected",
  "(observed - expected) / observed",
  "observed x expected"],
 0,
 "The chi-square statistic = sum over cells of (observed - expected)^2 / expected."),

("Testing whether two categorical variables (e.g., sector and credit-rating category) are related is BEST handled with a:",
 ["chi-square test of independence",
  "paired comparisons t-test",
  "Gordon growth model"],
 0,
 "Relationships between two categorical variables are tested with a chi-square test of independence using a contingency table."),

("If a correlation test fails to reject H0: rho = 0, the analyst concludes that:",
 ["the observed correlation could plausibly be due to chance",
  "the variables are definitely strongly correlated",
  "the correlation equals exactly +1"],
 0,
 "Failing to reject H0: rho = 0 means the evidence is insufficient to conclude a real (non-chance) linear relationship exists."),

("Both parametric and nonparametric tests of correlation aim to assess whether a relationship between two variables:",
 ["is the result of chance",
  "is caused by inflation",
  "violates the no-arbitrage condition"],
 0,
 "A significance test of correlation assesses whether the observed relationship between two variables is merely the result of chance."),
],

"Module 10: Simple Linear Regression": [
("In a simple linear regression, the variable we wish to explain is the:",
 ["dependent variable", "independent variable", "residual"],
 0,
 "The dependent variable is the one being explained; the independent variable is used to explain it."),

("Simple linear regression estimates the slope and intercept using which approach?",
 ["Ordinary least squares", "Maximum range", "Geometric averaging"],
 0,
 "Simple linear regression uses ordinary least squares (OLS) to estimate the intercept and slope parameters."),

("The least squares criterion minimizes the sum of the:",
 ["squared vertical distances between observations and the regression line",
  "absolute slopes of the line",
  "values of the independent variable"],
 0,
 "OLS minimizes the sum of squared residuals (squared vertical distances between actual Y values and the fitted line)."),

("Which of the following is NOT one of the four assumptions of the simple linear regression model?",
 ["Linearity", "Homoskedasticity", "Multicollinearity"],
 2,
 "The four assumptions are linearity, homoskedasticity, independence, and normality. Multicollinearity relates to multiple regression, not simple regression."),

("Homoskedasticity refers to the assumption that the:",
 ["variance of the residuals is constant across observations",
  "residuals are perfectly correlated",
  "independent variable is random"],
 0,
 "Homoskedasticity means the residual variance is constant across all observations."),

("The independence assumption in simple linear regression means that the:",
 ["X-Y pairs are uncorrelated across observations",
  "intercept equals zero",
  "residuals have non-constant variance"],
 0,
 "Independence requires that observations (X-Y pairs) be uncorrelated; patterns like seasonality suggest autocorrelation, violating it."),

("The normality assumption in simple linear regression requires that the:",
 ["residuals be normally distributed",
  "raw data themselves be normally distributed",
  "independent variable be normally distributed"],
 0,
 "Normality requires the residuals (not the raw data) to be normally distributed."),

("The total variation in the dependent variable (SST) can be decomposed into:",
 ["explained variation (SSR) plus unexplained variation (SSE)",
  "the slope plus the intercept",
  "the mean plus the median"],
 0,
 "SST = SSR (sum of squares regression, explained) + SSE (sum of squares error, unexplained)."),

("The coefficient of determination (R-squared) is BEST interpreted as the:",
 ["proportion of the total variation in Y explained by the regression",
  "slope of the regression line",
  "standard error of the estimate"],
 0,
 "R-squared = SSR/SST is the fraction of total variation in the dependent variable explained by the independent variable."),

("In a simple linear regression, the coefficient of determination equals the:",
 ["square of the correlation coefficient between X and Y",
  "correlation coefficient itself",
  "slope coefficient"],
 0,
 "In simple linear regression, R-squared equals the square of the correlation between X and Y."),

("The standard error of the estimate (SEE) measures the:",
 ["standard deviation of the regression residuals",
  "slope of the regression",
  "total variation in X"],
 0,
 "The SEE measures the dispersion of actual Y values around the fitted regression line (the standard deviation of residuals)."),

("A smaller standard error of the estimate indicates that the regression:",
 ["fits the data more closely",
  "fits the data less closely",
  "has a larger intercept"],
 0,
 "A smaller SEE means observations lie closer to the regression line - a better fit."),

("Analysis of variance (ANOVA) in regression is used to:",
 ["evaluate the overall fit and significance of the regression",
  "compute the present value of cash flows",
  "rank the residuals"],
 0,
 "ANOVA decomposes variation (SST into SSR and SSE) and supports the F-test of overall regression significance."),

("The F-statistic in a simple linear regression tests whether the:",
 ["regression as a whole is statistically significant (slope differs from zero)",
  "residuals are normally distributed",
  "intercept equals the mean of Y"],
 0,
 "The F-test assesses overall fit; in simple regression it tests whether the slope coefficient differs from zero."),

("To test whether a regression slope coefficient is statistically different from zero, the analyst uses a:",
 ["t-test on the estimated slope",
  "chi-square test",
  "test of the coefficient of variation"],
 0,
 "A t-test (estimated coefficient divided by its standard error) is used to test whether the slope differs from zero."),

("In the regression Y = b0 + b1X, the slope coefficient b1 represents the:",
 ["change in Y for a one-unit change in X",
  "value of Y when X is zero",
  "correlation between X and Y"],
 0,
 "The slope b1 is the expected change in the dependent variable Y for a one-unit change in the independent variable X."),

("In the regression Y = b0 + b1X, the intercept b0 represents the:",
 ["expected value of Y when X equals zero",
  "change in Y per unit change in X",
  "standard error of the estimate"],
 0,
 "The intercept b0 is the expected value of the dependent variable when the independent variable equals zero."),

("A prediction interval for a forecasted value of the dependent variable accounts for:",
 ["uncertainty in the regression model and the residual variability",
  "only the slope coefficient",
  "the mean of X alone"],
 0,
 "A prediction interval incorporates the uncertainty of the estimated regression and the variability of the residuals around the prediction."),

("Residual plots are used in regression analysis primarily to:",
 ["detect violations of the regression assumptions",
  "compute the dividend growth rate",
  "rank the independent variables"],
 0,
 "Residual plots help reveal violations such as heteroskedasticity, non-linearity, or autocorrelation."),

("A pattern (e.g., seasonality) in a plot of regression residuals over time MOST likely indicates a violation of the assumption of:",
 ["independence (suggesting autocorrelation)",
  "linearity",
  "a zero intercept"],
 0,
 "A systematic pattern such as seasonality in residuals suggests autocorrelation, violating the independence assumption."),
],

"Module 11: Introduction to Big Data Techniques": [
("Big Data is commonly characterized by the 'three Vs', which are:",
 ["volume, velocity, and variety",
  "value, volatility, and volume",
  "velocity, validity, and value"],
 0,
 "Big Data is characterized by the three Vs: volume, velocity, and variety."),

("When Big Data is used for inference or prediction, an important fourth 'V' to consider is:",
 ["veracity", "volatility", "value"],
 0,
 "A fourth V - veracity (data quality/reliability) - becomes important when Big Data is used for inference or prediction."),

("The term 'fintech' MOST broadly refers to:",
 ["technology-driven innovation in the financial services industry",
  "a specific type of government bond",
  "a method of computing portfolio variance"],
 0,
 "Fintech refers to technology-driven innovation in the design and delivery of financial services and products."),

("Which of the following are among the main sources of ALTERNATIVE data?",
 ["Individuals, business processes, and sensors",
  "Only corporate financial statements",
  "Only government economic releases"],
 0,
 "Main sources of alternative data are data generated by individuals, business processes, and sensors."),

("Artificial intelligence (AI) is BEST described as computer systems capable of:",
 ["performing tasks that traditionally required human intelligence",
  "only storing large datasets",
  "executing only fixed, pre-programmed rules"],
 0,
 "AI systems perform tasks traditionally requiring human intelligence at levels comparable or superior to humans."),

("Machine learning (ML) is BEST summarized by the phrase:",
 ["'find the pattern, apply the pattern'",
  "'buy low, sell high'",
  "'minimize the sum of squared errors'"],
 0,
 "ML seeks to extract knowledge by learning from examples - 'find the pattern, apply the pattern'."),

("Which of the following is a main TYPE of machine learning?",
 ["Supervised learning", "Convenience learning", "Judgmental learning"],
 0,
 "Main types of ML include supervised learning, unsupervised learning, and deep learning."),

("In supervised learning, the algorithm is trained using:",
 ["labeled data (inputs paired with known outputs)",
  "only unlabeled data",
  "no data at all"],
 0,
 "Supervised learning uses labeled data - inputs paired with known target outputs - to learn to predict."),

("Unsupervised learning differs from supervised learning in that it:",
 ["works with unlabeled data to find structure or groupings",
  "always requires labeled outputs",
  "can only be used for bond pricing"],
 0,
 "Unsupervised learning uses unlabeled data, seeking to discover structure (e.g., clusters) without predefined target outputs."),

("Natural language processing (NLP) is an application of text analytics that:",
 ["analyzes and interprets text- and voice-based data using the structure of human language",
  "computes the variance of returns",
  "ranks bonds by credit quality only"],
 0,
 "NLP uses insight into the structure of human language to analyze and interpret text- and voice-based data."),

("Deep learning is BEST described as a type of:",
 ["machine learning", "fixed rule-based system", "sampling method"],
 0,
 "Deep learning is one of the main types of machine learning."),

("Among the developments most relevant to quantitative investment analysis is the:",
 ["analysis of large traditional and alternative datasets",
  "elimination of all financial data",
  "exclusive use of paper records"],
 0,
 "Fintech-driven analysis of large datasets - both traditional and alternative - is directly relevant to quantitative investment analysis."),

("Alternative data generated by SENSORS would MOST likely include:",
 ["satellite imagery or Internet-of-Things device readings",
  "a company's audited income statement",
  "a central bank interest-rate announcement"],
 0,
 "Sensor-generated alternative data includes satellite imagery, IoT readings, and similar machine-collected data."),

("Alternative data generated by INDIVIDUALS would MOST likely include:",
 ["social media posts and online reviews",
  "corporate 10-K filings",
  "exchange-reported trading volumes"],
 0,
 "Individual-generated alternative data includes social media posts, product reviews, and web search activity."),

("A primary motivation for integrating alternative data into investment processes is to:",
 ["help generate alpha and reduce losses",
  "eliminate the need for any analysis",
  "guarantee positive returns"],
 0,
 "Alternative data can be integrated into investment decision-making to help generate alpha and reduce losses."),

("Early forms of fintech primarily involved:",
 ["data processing and automation of routine tasks",
  "complex deep-learning trading systems",
  "natural language processing of voice data"],
 0,
 "Early fintech involved data processing and automation of routine tasks, later advancing to complex machine-learning applications."),

("'Veracity' as a characteristic of Big Data refers to the data's:",
 ["truthfulness, quality, and reliability",
  "speed of arrival",
  "physical storage size"],
 0,
 "Veracity concerns the truthfulness/reliability of the data - critical when using Big Data for inference or prediction."),

("'Velocity' as one of the three Vs of Big Data refers to the:",
 ["speed at which data are created and become available",
  "total quantity of data",
  "diversity of data formats"],
 0,
 "Velocity refers to how quickly data are generated and made available; volume is quantity and variety is the diversity of formats."),

("'Variety' as one of the three Vs of Big Data refers to the:",
 ["range of data types and sources, including structured and unstructured data",
  "reliability of the data",
  "rate of data generation"],
 0,
 "Variety refers to the diverse types and sources of data, spanning structured and unstructured (traditional and alternative) data."),

("Fundamental asset managers are described as using Big Data and ML tools to engage in:",
 ["hybrid forms of investment decision making",
  "purely manual stock picking only",
  "eliminating all quantitative inputs"],
 0,
 "These tools affect not only quant managers but also fundamental managers, who use them in hybrid forms of investment decision making."),
],
}


if __name__ == "__main__":
    total = sum(len(v) for v in QUESTION_BANK.values())
    for topic, qs in QUESTION_BANK.items():
        print(f"{topic}: {len(qs)} questions")
    print(f"TOTAL: {total} questions across {len(QUESTION_BANK)} topics")
