const VIDEO_LIBRARY = {
  // ===== VOLUME 1: QUANTITATIVE METHODS =====
  "1-1": [
    { title: "Determinants of Interest Rates", url: "https://youtu.be/b_VfeLX9yVA" },
    { title: "Holding Period, Arithmetic, Geometric Mean Returns", url: "https://youtu.be/DcCa74GHM50" },
    { title: "Extreme Values – Harmonic, Trimmed, Windsorized Means", url: "https://youtu.be/4Tr0PP9m3N4" },
    { title: "Special Return Measures", url: "https://youtu.be/Misj1xqAsNU" },
    { title: "Money-Weighted and Time-Weighted Rates of Return", url: "https://youtu.be/JQNIpJGbhB0" },
    { title: "Annualized Returns", url: "https://youtu.be/Ro6p2Wb9_5M" },
  ],
  "1-2": [
    { title: "Formatting the TI BA II Plus Calculator", url: "https://youtu.be/2BHL9PfyUSU" },
    { title: "TVM – Future Value", url: "https://youtu.be/QPwxWo5GjhA" },
    { title: "TVM – Present Value", url: "https://youtu.be/IXO4L3lVA-4" },
    { title: "TVM – Number of Periods", url: "https://youtu.be/u02cjdJ10tI" },
    { title: "TVM – Interest Rate", url: "https://youtu.be/uCwijJwx2R8" },
    { title: "TVM – Annuities", url: "https://youtu.be/E39PqJOZEpQ" },
    { title: "TVM – Perpetuities", url: "https://youtu.be/Oz3O6D9BenE" },
    { title: "TVM – Unequal Cash Flows", url: "https://youtu.be/B9AxD39BbkA" },
    { title: "TVM – Computing PMT", url: "https://youtu.be/Yhz4H5Qfx6o" },
    { title: "TVM – Complex Problems", url: "https://youtu.be/FPfHQDpoEO0" },
  ],
  "1-3": [
    { title: "Properties of the Arithmetic Mean", url: "https://youtu.be/lxySuPkjq7M" },
    { title: "Mode and Median", url: "https://youtu.be/Sm4LGWYhxl8" },
    { title: "Dealing with Outliers", url: "https://youtu.be/kzGibUtrUUE" },
    { title: "Quartiles and Quintiles", url: "https://youtu.be/XXLl9yG-s0A" },
    { title: "Deciles and Percentiles", url: "https://youtu.be/6vp_EQmSuhU" },
    { title: "Measures of Location Continued", url: "https://youtu.be/zwJ9UInXkC8" },
    { title: "Range and Mean Absolute Deviation", url: "https://youtu.be/kZblOZOSqQc" },
    { title: "Sample Variance and Standard Deviation", url: "https://youtu.be/D2o_FS9Ma5E" },
    { title: "Downside Deviation and Coefficient of Variation", url: "https://youtu.be/7H5d_4XDopo" },
    { title: "Skewness", url: "https://youtu.be/6Yy8jBm8TYk" },
    { title: "Kurtosis", url: "https://youtu.be/kWUdGPTj6tY" },
    { title: "Correlation", url: "https://youtu.be/bPAM3Nb6ix8" },
  ],
  "1-4": [
    { title: "Expected Value and Variance", url: "https://youtu.be/GP690YGdo8g" },
    { title: "Probability Trees and Conditional Expectations", url: "https://youtu.be/G5QFIuQLqVE" },
    { title: "Bayes' Formula", url: "https://youtu.be/F3L1n1f0k30" },
  ],
  "1-5": [
    { title: "Expected Portfolio Return", url: "https://youtu.be/8-eBkSNFDag" },
    { title: "Standard Deviation and Variance of Expected Returns", url: "https://youtu.be/fLHwDy_pUM8" },
    { title: "Covariance and Correlation from Joint Probability", url: "https://youtu.be/lKVU3IF3dmY" },
    { title: "Portfolio Variance for Two-Asset Portfolio", url: "https://youtu.be/xoYWMKIMOTU" },
    { title: "Portfolio Risk Measures", url: "https://youtu.be/qB1F2PaiU10" },
  ],
  "1-6": [
    { title: "Lognormal Distribution and Continuous Compounding", url: "https://youtu.be/wVb6qoGh-bY" },
    { title: "Monte Carlo Simulation and Bootstrapping", url: "https://youtu.be/h_9AxbCgFKk" },
  ],
  "1-7": [
    { title: "Sampling Methods", url: "https://youtu.be/pk601B4T7Fs" },
    { title: "Central Limit Theorem and Bootstrapping", url: "https://youtu.be/t1hxZUPz61I" },
  ],
  "1-8": [
    { title: "Hypothesis Testing Overview", url: "https://youtu.be/BnFm5vwFLyM" },
    { title: "Tests of a Single Mean", url: "https://youtu.be/YzmsHThcYlg" },
    { title: "Tests of Difference in Means", url: "https://youtu.be/JjMPUp-rIOk" },
    { title: "Tests of Mean of Differences", url: "https://youtu.be/LKa3ke606ko" },
    { title: "Tests of a Single Variance", url: "https://youtu.be/U5z4mR2Vyx0" },
    { title: "Tests of Equality of Two Variances", url: "https://youtu.be/SAvG1MdXft4" },
    { title: "Parametric vs. Nonparametric Tests", url: "https://youtu.be/hOS3p4yyi_A" },
  ],
  "1-9": [
    { title: "Parametric Tests of Correlation", url: "https://youtu.be/XbXFZ3vaoUs" },
    { title: "Non-parametric Tests of Correlation", url: "https://youtu.be/aw3iW7HxF48" },
    { title: "Tests of Independence Using Contingency Tables", url: "https://youtu.be/ozIpx8TBKPw" },
  ],
  "1-10": [
    { title: "Linear Regression Basics", url: "https://youtu.be/Gc8H9GwXGJw" },
    { title: "Estimating Parameters of Simple Linear Regression", url: "https://youtu.be/NB-UswOIp7E" },
    { title: "Assumptions of Simple Linear Regression", url: "https://youtu.be/6LK4z7j61_o" },
    { title: "Analysis of Variance and Goodness of Fit", url: "https://youtu.be/xYqzvkyfjII" },
    { title: "Hypothesis Tests of Slope Coefficient", url: "https://youtu.be/84l3v6VDePE" },
    { title: "Hypothesis Tests of Intercept", url: "https://youtu.be/cygNFuHYZGw" },
    { title: "ANOVA and Standard Error of Estimate", url: "https://youtu.be/-8jjzTHwJyA" },
    { title: "Prediction Using Simple Linear Regression", url: "https://youtu.be/TBK4TCVRH14" },
    { title: "Functional Forms for Simple Linear Regression", url: "https://youtu.be/YxezTQPYnN8" },
  ],
  "1-11": [
    { title: "Fintech in Quantitative Investment Analysis", url: "https://youtu.be/wmml0661-Pw" },
    { title: "Advanced Analytical Tools: AI and Machine Learning", url: "https://youtu.be/PexlKC-SSBY" },
    { title: "Tackling Big Data with Data Science", url: "https://youtu.be/UB0-Li-oifI" },
  ],

  // ===== VOLUME 2: ECONOMICS =====
  "2-1": [
    { title: "Profit Maximization", url: "https://youtu.be/kTVAI4tEKNo" },
    { title: "Production Breakeven and Shutdown Decision", url: "https://youtu.be/9mJzzZz9PHM" },
    { title: "Economies and Diseconomies of Scale", url: "https://youtu.be/AxQ87sj2JGE" },
    { title: "Market Structures", url: "https://youtu.be/iQEh6eyWKrc" },
    { title: "Monopolistic Competition", url: "https://youtu.be/9TFI0kfR_LQ" },
    { title: "Pricing Interdependence and Cournot Assumption", url: "https://youtu.be/GJ8d05hm2KA" },
    { title: "Nash Equilibrium and Collusion", url: "https://youtu.be/mr0pdOY6hEw" },
    { title: "Determining Market Structure", url: "https://youtu.be/u40l1EMjMpU" },
  ],
  "2-2": [
    { title: "Overview of the Business Cycle", url: "https://youtu.be/pBYf3fJfQ94" },
    { title: "Credit Cycles", url: "https://youtu.be/yXIzGl4lMiI" },
    { title: "Economic Indicators", url: "https://youtu.be/jms4GnSpSxU" },
  ],
  "2-3": [
    { title: "Fiscal Policy Roles and Objectives", url: "https://youtu.be/mtLUpe1wByA" },
    { title: "Deficits and National Debt", url: "https://youtu.be/ArlkQHbTvLA" },
    { title: "Fiscal Policy Tools", url: "https://youtu.be/KQSLzkWPb8E" },
    { title: "Fiscal Policy Implementation", url: "https://youtu.be/U9VJSMrvKis" },
  ],
  "2-4": [
    { title: "Role of Central Banks", url: "https://youtu.be/FpmFqhoy2nk" },
    { title: "Monetary Policy Tools and Transmission", url: "https://youtu.be/SRqcQMeSkGc" },
    { title: "Monetary Policy Objectives", url: "https://youtu.be/UpFY0UYbT9A" },
    { title: "Contractionary and Expansionary Monetary Policy", url: "https://youtu.be/VKfINS8zxSk" },
    { title: "Interaction Between Monetary and Fiscal Policy", url: "https://youtu.be/hf2LH-UR27w" },
  ],
  "2-5": [
    { title: "National Governments and Political Cooperation", url: "https://youtu.be/nMyB7q5dkYA" },
    { title: "Forces of Globalization", url: "https://youtu.be/0pSYHK55Igw" },
    { title: "International Trade Organizations", url: "https://youtu.be/g8SjHq_aTQ0" },
    { title: "Assessing Geopolitical Actors and Risk", url: "https://youtu.be/Wq-kjRfxhB8" },
    { title: "The Tools of Geopolitics", url: "https://youtu.be/k2v_ZVKr134" },
    { title: "Geopolitical Risk and the Investment Process", url: "https://youtu.be/0_AQgxChnhc" },
  ],
  "2-6": [
    { title: "Benefits and Costs of Trade", url: "https://youtu.be/560IywhNJoc" },
    { title: "Tariffs, Quotas and Subsidies", url: "https://youtu.be/uI28pVIQklw" },
    { title: "Regional Trade Agreements", url: "https://youtu.be/ZcNNQkwWGMg" },
    { title: "Regional Integration", url: "https://youtu.be/HOaD43V8uK0" },
  ],
  "2-7": [
    { title: "The Foreign Exchange Market and Exchange Rates", url: "https://youtu.be/VzPwvxeHpWA" },
    { title: "Exchange Rate Regimes", url: "https://youtu.be/Aha6Iio4n1Y" },
    { title: "Capital Restrictions", url: "https://youtu.be/vrTfz-tHfYI" },
  ],
  "2-8": [
    { title: "Computing Cross-Rates", url: "https://youtu.be/HXDqMomIMAE" },
    { title: "Computing Forward Rates", url: "https://youtu.be/M_QMa_s4FS0" },
  ],

  // ===== VOLUME 3: CORPORATE ISSUERS =====
  "3-1": [
    { title: "Organizational Forms and Corporate Issuer Features", url: "https://youtu.be/BXH9_cGRMbE" },
    { title: "Publicly vs. Privately Owned Corporate Issuers", url: "https://youtu.be/hFbZUOERU6I" },
  ],
  "3-2": [
    { title: "Financial Claims of Lenders and Shareholders", url: "https://youtu.be/CkHzTiiqSDs" },
    { title: "Corporate Stakeholders and Governance", url: "https://youtu.be/tjIM5mROgl4" },
    { title: "Corporate ESG Considerations", url: "https://youtu.be/YODoaEHaz6g" },
  ],
  "3-3": [
    { title: "Stakeholder Conflicts and Management", url: "https://youtu.be/ENfu4yGklLI" },
    { title: "Corporate Governance Mechanisms", url: "https://youtu.be/2H-U8Cgt5gU" },
    { title: "Corporate Governance Risks and Benefits", url: "https://youtu.be/7tJYCF8lI3g" },
  ],
  "3-4": [
    { title: "Cash Conversion Cycle", url: "https://youtu.be/r2DOfwRmXCk" },
    { title: "Liquidity", url: "https://youtu.be/OLbTuHj4yt0" },
    { title: "Managing Working Capital and Liquidity", url: "https://youtu.be/qiTp3q9meCU" },
  ],
  "3-5": [
    { title: "Capital Investments", url: "https://youtu.be/for1fEARSTk" },
    { title: "NPV and IRR Computation", url: "https://youtu.be/9NOyRybYO88" },
    { title: "Capital Allocation", url: "https://youtu.be/utmvkRYF-_Y" },
    { title: "Return on Invested Capital", url: "https://youtu.be/C9JseHKu4x4" },
    { title: "Capital Allocation Principles and Pitfalls", url: "https://youtu.be/6pkLTANvxus" },
    { title: "Real Options", url: "https://youtu.be/1fBkV8pXwx8" },
  ],
  "3-6": [
    { title: "Computing WACC from Multiple Capital Sources", url: "https://youtu.be/Pt43KhjkTfo" },
    { title: "Factors Affecting Capital Structure", url: "https://youtu.be/SOXK-wnFJN4" },
    { title: "Modigliani-Miller Capital Structure Propositions", url: "https://youtu.be/85z8J9hs7r8" },
    { title: "Optimal Capital Structure", url: "https://youtu.be/JWyOOEAFiD8" },
  ],
  "3-7": [
    { title: "Business Model Features and the Value Proposition", url: "https://youtu.be/qH-IUluSp60" },
    { title: "Pricing and Revenue Models", url: "https://youtu.be/GF4W-jnhP5Q" },
    { title: "Business Organization and Capabilities", url: "https://youtu.be/MaOzrkvTXKg" },
    { title: "Business Model Types", url: "https://youtu.be/cNblM4dLSrc" },
  ],

  // ===== VOLUME 4: FINANCIAL STATEMENT ANALYSIS =====
  "4-1": [
    { title: "Financial Statement Analysis", url: "https://youtu.be/WHQIidz3QkQ" },
    { title: "Sources of Information", url: "https://youtu.be/hePbHp8GpyU" },
    { title: "Segment Reporting", url: "https://youtu.be/DySmtPJm5dU" },
    { title: "IFRS vs. Alternative Reporting Systems", url: "https://youtu.be/y7V9OzGFm6Y" },
  ],
  "4-2": [
    { title: "Revenue Recognition", url: "https://youtu.be/q2Tzos6ZStM" },
    { title: "Expense Recognition", url: "https://youtu.be/sSIbJQm0x0g" },
    { title: "Capitalization of Interest", url: "https://youtu.be/9ILsvAlT4xw" },
    { title: "Non-recurring Items", url: "https://youtu.be/NNkXU3bqYjA" },
    { title: "Changes in Accounting Estimates vs. Policies", url: "https://youtu.be/GgKcukfpfuU" },
    { title: "Basic EPS", url: "https://youtu.be/mpqNbU8gB3M" },
    { title: "Diluted EPS", url: "https://youtu.be/bKopwh2GnMU" },
    { title: "Income Statement Ratios and Common-Size Analysis", url: "https://youtu.be/WxUTIIxsDbE" },
  ],
  "4-3": [
    { title: "Intangible Assets", url: "https://youtu.be/mtaK2qzRNyE" },
    { title: "Goodwill", url: "https://youtu.be/rpkLSH01oGg" },
    { title: "Gain on a Bargain Purchase", url: "https://youtu.be/p6kfA7itafA" },
    { title: "Accounting for Financial Instruments", url: "https://youtu.be/eKAR2ZcYb-8" },
    { title: "Non-current Liabilities", url: "https://youtu.be/TBa01gBryeA" },
    { title: "Balance Sheet Ratios and Common-Size Analysis", url: "https://youtu.be/0Nt2-v6UU7o" },
  ],
  "4-4": [
    { title: "Cash Flows from Operations – Direct Method", url: "https://youtu.be/owW695A5nko" },
    { title: "Cash Flows from Operations – Indirect Method", url: "https://youtu.be/NsZoZYYz1cU" },
    { title: "Cash Flows from Investing – Purchases of PPE", url: "https://youtu.be/mfpV6gzNr0g" },
    { title: "Cash Flow Problems – Part 1", url: "https://youtu.be/xRUqTuGsPGU" },
    { title: "Cash Flow Problems – Part 2", url: "https://youtu.be/2zfNePGNn9o" },
  ],
  "4-5": [
    { title: "Evaluating Sources and Uses of Cash", url: "https://youtu.be/utMGN3PvwLE" },
    { title: "Cash Flow Ratios and Common-Size Analysis", url: "https://youtu.be/cSBVdaPhM1U" },
  ],
  "4-6": [
    { title: "Inventory – Initial Measurement", url: "https://youtu.be/Ca0aM513tY8" },
    { title: "Inventory – Cost vs. NRV: Write-downs", url: "https://youtu.be/M8b7TurBmxs" },
    { title: "Inventory: Write-down Reversals", url: "https://youtu.be/OGSVHPwmlMc" },
    { title: "FIFO – First in First Out", url: "https://youtu.be/CvrlMp5DmT8" },
    { title: "LIFO – Last In First Out", url: "https://youtu.be/PB-p7ouadiE" },
    { title: "Weighted Average Cost (AVCO)", url: "https://youtu.be/xmW1fjj6HcI" },
    { title: "Accounting for Inventories – Overview", url: "https://youtu.be/GqAJNwudknA" },
  ],
  "4-7": [
    { title: "Acquisition of Intangible Assets", url: "https://youtu.be/G72KPutr834" },
    { title: "Intangible Assets", url: "https://youtu.be/qCmSVH3CZas" },
    { title: "Asset Impairment", url: "https://youtu.be/oeddB1LXE-M" },
    { title: "Impairment Under IFRS", url: "https://youtu.be/OfCEDHeAwj8" },
    { title: "Impairment Under US GAAP", url: "https://youtu.be/HRZ2paRSe5w" },
    { title: "Asset Derecognition", url: "https://youtu.be/xw4ONZ6ep1E" },
    { title: "Analysis of Long-lived Assets", url: "https://youtu.be/dShN5AiF6XU" },
  ],
  "4-8": [
    { title: "Accounting for Leases", url: "https://youtu.be/XZhLatcEH0M" },
    { title: "Accounting for Pension Plans", url: "https://youtu.be/n9FffHBAHWE" },
    { title: "Accounting for Share-based Compensation", url: "https://youtu.be/Dd-8juITzEg" },
  ],
  "4-9": [
    { title: "Deferred Tax Playlist (9 videos)", url: "https://www.youtube.com/playlist?list=PLzsMtRJ44d8xpqKLcXDYPtXEJwDs2SqYD" },
  ],
  "4-10": [
    { title: "Financial Reporting Quality Spectrum", url: "https://youtu.be/2EKb4t1lrwk" },
    { title: "GAAP, Decision Useful Financial Reporting", url: "https://youtu.be/02s6RX2ThYU" },
    { title: "Biased Accounting Choices", url: "https://youtu.be/U2RAWaxU8ik" },
    { title: "Conservative vs. Aggressive Accounting", url: "https://youtu.be/6bt8Xsy9RPE" },
    { title: "Context for Assessing Reporting Quality", url: "https://youtu.be/HMlfF96E38A" },
    { title: "Mechanisms Disciplining Reporting Quality", url: "https://youtu.be/wrau5zHXHiU" },
    { title: "Detection of Reporting Quality Issues", url: "https://youtu.be/wo7e4yhRHmU" },
    { title: "Accounting Choices and Estimates", url: "https://youtu.be/i5AqO6K_TsA" },
    { title: "Accounting Warning Signs", url: "https://youtu.be/0SF2C1Pj2o0" },
  ],
  "4-11": [
    { title: "Financial Analysis Process, Tools and Techniques", url: "https://youtu.be/F8M-P127a88" },
    { title: "Financial Ratio Analysis", url: "https://youtu.be/VOrrUfHi1qQ" },
    { title: "Activity Ratios", url: "https://youtu.be/w6_eiS2j5FQ" },
    { title: "Liquidity Ratios", url: "https://youtu.be/y8vueSgPiTU" },
    { title: "Solvency Ratios", url: "https://youtu.be/RO_aJnug54M" },
    { title: "Profitability Ratios", url: "https://youtu.be/DqkjDuiAIJY" },
    { title: "DuPont Analysis", url: "https://youtu.be/-8ZCKJTNelw" },
    { title: "Industry-specific Financial Ratios", url: "https://youtu.be/1jWGL6mbyfU" },
  ],
  "4-12": [
    { title: "Building a Financial Statement Model", url: "https://youtu.be/DnTCN3X_qRY" },
    { title: "Behavioral Finance and Analyst Forecasts", url: "https://youtu.be/SLOd8Mtwq6o" },
    { title: "Impact of Competitive Factors on Prices and Costs", url: "https://youtu.be/SBKJxoxPeI8" },
    { title: "Modeling Inflation and Deflation", url: "https://youtu.be/GB6Q2UnXOUw" },
    { title: "The Forecast Horizon and Long-term Forecasting", url: "https://youtu.be/4RRmeAcbfOA" },
  ],

  // ===== VOLUME 5: EQUITY INVESTMENTS =====
  "5-1": [
    { title: "Overview of the Financial System", url: "https://youtu.be/klj6h62Dl3Y" },
    { title: "Assets and Contracts", url: "https://youtu.be/KbVeupYAPxQ" },
    { title: "Securities", url: "https://youtu.be/2poZhd3e2h8" },
    { title: "Currencies, Commodities and Real Assets", url: "https://youtu.be/c7gT_EZZNJs" },
    { title: "Financial Intermediaries", url: "https://youtu.be/ifjTShvwfFA" },
    { title: "Securitizers, Depositary Institutions and Insurers", url: "https://youtu.be/d5whUPIQyy8" },
    { title: "Settlement and Custodial Services", url: "https://youtu.be/LC3UfAICGRc" },
    { title: "Positions and Short Positions", url: "https://youtu.be/RKJBxCKaiWk" },
    { title: "Maintenance Margin", url: "https://youtu.be/_M5Ce7swPnY" },
    { title: "Orders and Execution Instructions", url: "https://youtu.be/25OniowBj7Q" },
    { title: "Validity and Clearing Instructions", url: "https://youtu.be/_AoN0kqDL7s" },
    { title: "Primary Security Markets", url: "https://youtu.be/o9_DW1LNqyw" },
    { title: "Secondary Security Markets", url: "https://youtu.be/-mxA9i76ej4" },
    { title: "Well-functioning Financial Systems", url: "https://youtu.be/WpLOWqw8hyc" },
    { title: "Market Regulation", url: "https://youtu.be/33stwVnkh6A" },
  ],
  "5-2": [
    { title: "Index Definition and Construction", url: "https://youtu.be/GecUTe5Oskg" },
    { title: "Rebalancing and Reconstitution", url: "https://youtu.be/Cuq5w5OHbow" },
    { title: "Uses of Market Indexes", url: "https://youtu.be/dIg25PZxKKQ" },
    { title: "Equity Indexes", url: "https://youtu.be/Fau9NhpKGZ8" },
    { title: "Fixed-income Indexes", url: "https://youtu.be/nqNydBgEnYE" },
    { title: "Indexes for Alternative Investments", url: "https://youtu.be/igOSccfo5xA" },
  ],
  "5-3": [
    { title: "Market Efficiency", url: "https://youtu.be/g4_k-5OmX7E" },
    { title: "Forms of Market Efficiency", url: "https://youtu.be/opKlU56hfpc" },
    { title: "Time-series and Cross-sectional Anomalies", url: "https://youtu.be/uRtgNT81fPI" },
    { title: "Market Anomalies", url: "https://youtu.be/xouiyfIwKtE" },
    { title: "Behavioral Finance", url: "https://youtu.be/33jF5Luw7Ks" },
  ],
  "5-4": [
    { title: "Ordinary and Preferred Shares", url: "https://youtu.be/Y2b-x4UOEwE" },
    { title: "Public vs. Private Equity Securities", url: "https://youtu.be/gjM8MLUMUTg" },
    { title: "Non-domestic Equity Securities", url: "https://youtu.be/fLncZkgDj3s" },
    { title: "Equity Risk and Return", url: "https://youtu.be/FZhXFpx7tcQ" },
    { title: "Equity and Company Value", url: "https://youtu.be/tSIBmZLkfdE" },
  ],
  "5-5": [
    { title: "Company Research Reports", url: "https://youtu.be/-mvBNYxPslg" },
    { title: "Determining the Business Model", url: "https://youtu.be/vPahQBcdHcY" },
    { title: "Revenue Analysis", url: "https://youtu.be/K8ygM0iQ14M" },
    { title: "Operating Profitability and Working Capital Analysis", url: "https://youtu.be/ti6HhRQmHGE" },
    { title: "Capital Investments and Capital Structure", url: "https://youtu.be/6uVZiJw37FQ" },
  ],
  "5-6": [
    { title: "Uses of Industry Analysis", url: "https://youtu.be/dpK5bQb_4jI" },
    { title: "Industry Classification", url: "https://youtu.be/W8BXjR-OaUE" },
    { title: "Industry Survey", url: "https://youtu.be/ncaT_VjI9iA" },
    { title: "Industry Structure and External Influences", url: "https://youtu.be/05beMZePrYw" },
    { title: "Competitive Positioning", url: "https://youtu.be/xMIGa70tk00" },
  ],
  "5-7": [
    { title: "Forecast Objects, Principles and Approaches", url: "https://youtu.be/fTq_QA7bWz4" },
    { title: "Forecasting Revenues", url: "https://youtu.be/_h8oM_nkT6M" },
    { title: "Forecasting Operating Expenses and Working Capital", url: "https://youtu.be/nSWanwFcOm4" },
    { title: "Forecasting CAPEX and Capital Structure", url: "https://youtu.be/awBbIWiPvJ8" },
  ],
  "5-8": [
    { title: "The DDM, GGM and FCFE", url: "https://youtu.be/aVHA0Kiivk8" },
    { title: "Dividend Payments Explained", url: "https://youtu.be/YXpqIOuYHSc" },
    { title: "Valuing Preferred Shares", url: "https://youtu.be/9FZTEu1RqaM" },
    { title: "Gordon Growth Model – No g Term Provided", url: "https://youtu.be/7ISitiyiumE" },
    { title: "Gordon Growth Model – No Current Dividend", url: "https://youtu.be/A-CMXZuwYAc" },
    { title: "Multistage Dividend Discount Models", url: "https://youtu.be/HNxOkdzO3rY" },
    { title: "Multiples and Comparables", url: "https://youtu.be/4ZLHK4-qy3Y" },
    { title: "Justified Forward P/E Ratio", url: "https://youtu.be/TxYoo2YUGyE" },
    { title: "Enterprise Value and Asset-based Valuation", url: "https://youtu.be/SdQomQbxjUE" },
  ],

  // ===== VOLUME 6: FIXED INCOME =====
  "6-1": [
    { title: "Fixed Income Instrument Features", url: "https://youtu.be/xAxFGGspAYg" },
    { title: "Coupon Rate, Payment Frequency and Yield Measures", url: "https://youtu.be/Lmpl3dQd314" },
    { title: "Question Crunch: Fixed Income Instrument Features", url: "https://youtu.be/HMh8yxKiVW8" },
    { title: "Bond Indenture and Covenants", url: "https://youtu.be/oRpQTy_seG8" },
    { title: "Question Crunch: Bond Indentures and Covenants", url: "https://youtu.be/dNx_Nbt98sY" },
  ],
  "6-2": [
    { title: "Fixed Income Cash Flows and Types", url: "https://youtu.be/ev_u96C-0qU" },
    { title: "Question Crunch: Cash Flows and Types", url: "https://youtu.be/EdAEdpTsrio" },
    { title: "Variable Interest, Zero-coupon and Deferred Coupon Bonds", url: "https://youtu.be/8LNH8MOOGrY" },
    { title: "Question Crunch: Variable Interest Debt", url: "https://youtu.be/GvWOoVYN-Sk" },
    { title: "Contingency Provisions – Callable, Putable, Convertible", url: "https://youtu.be/ZFelNphbHLQ" },
    { title: "Legal, Regulatory and Tax Considerations", url: "https://youtu.be/iBISJI8TB6g" },
    { title: "Question Crunch: Contingency, Legal, Tax", url: "https://youtu.be/qhpKpJHoa0Q" },
  ],
  "6-3": [
    { title: "Fixed Income Segments, Ratings and Indexes", url: "https://youtu.be/5QFXxFgadGA" },
    { title: "Question Crunch: Segments, Issuers, Indexes", url: "https://youtu.be/Nb3FnC5iJo4" },
    { title: "Primary and Secondary Fixed Income Markets", url: "https://youtu.be/rOiEJ7J_x0w" },
    { title: "Question Crunch: Primary and Secondary Markets", url: "https://youtu.be/yeBov5JPeeY" },
  ],
  "6-4": [
    { title: "Short-term Funding for Corporate Borrowers", url: "https://youtu.be/SWscnVSuH9w" },
    { title: "Short-term Funding for Financial Institutions", url: "https://youtu.be/UYUXQurjYq4" },
    { title: "Repurchase Agreements (Repo) Basics", url: "https://youtu.be/_Z7qZvnhdKE" },
    { title: "Repurchase Agreements (Repo) Applications and Risks", url: "https://youtu.be/LURWKJoi40w" },
    { title: "Long-term Corporate Debt", url: "https://youtu.be/BxOFpP-tT24" },
  ],
  "6-5": [
    { title: "Sovereign and Similar Debt", url: "https://youtu.be/GD-c83iUU6s" },
    { title: "Sovereign Debt Issuance and Trading", url: "https://youtu.be/ekC7EVvx_cg" },
  ],
  "6-6": [
    { title: "Bond Pricing and the TVM", url: "https://youtu.be/G8snxOaaFxU" },
    { title: "Question Crunch: Bond Pricing and TVM", url: "https://youtu.be/CWOnIfK2SSo" },
    { title: "Flat Price, Accrued Interest and the Full Price", url: "https://youtu.be/9utm3EZnOZU" },
    { title: "Using the Bond Worksheet for Pricing", url: "https://youtu.be/1YoiQ26uir4" },
    { title: "Question Crunch: Flat Price, Accrued Interest", url: "https://youtu.be/7f-ezpnnU-k" },
    { title: "Bond Prices and Bond Features Relationship", url: "https://youtu.be/yT6z8Xd6qsQ" },
    { title: "Bond Price and Yield Relationship", url: "https://youtu.be/KTErV_JhLJM" },
    { title: "Matrix Pricing", url: "https://youtu.be/cz_61NN7oVs" },
  ],
  "6-7": [
    { title: "Periodicity and Annualized Yields", url: "https://youtu.be/SnOaCwiS0eo" },
    { title: "Other Yield Measures and Conventions", url: "https://youtu.be/BrIJUWF-PqE" },
    { title: "Yield to Call and Yield to Worst", url: "https://youtu.be/m7s1Q-3QJfk" },
    { title: "G-spread", url: "https://youtu.be/BXWoYjXn2V0" },
    { title: "I-spread", url: "https://youtu.be/4WkMBJEmWZM" },
    { title: "Z-spread", url: "https://youtu.be/7QRVBQg2_RQ" },
    { title: "OAS – Option Adjusted Spread", url: "https://youtu.be/o9R5CrOpzl4" },
  ],
  "6-8": [
    { title: "Discount Margin / Required Margin", url: "https://youtu.be/AjiHnr_7V3Y" },
    { title: "Yield Measures for Money Market Instruments", url: "https://youtu.be/5kKBwL0qkhI" },
  ],
  "6-9": [
    { title: "Term Structure of Interest Rates and Spot Rates", url: "https://youtu.be/IBl5WfXgfJc" },
    { title: "Par and Forward Rates", url: "https://youtu.be/lJu86I7jdS4" },
    { title: "Spot, Par and Forward Yield Curves", url: "https://youtu.be/Z8tPrf66Mzc" },
  ],
  "6-10": [
    { title: "Sources of Return from Fixed-coupon Bonds", url: "https://youtu.be/m12xP7ZO5BU" },
    { title: "Investment Horizon and Interest Rate Risk", url: "https://youtu.be/j87d-5V_yIU" },
    { title: "Macaulay Duration", url: "https://youtu.be/3TqRsLX6iK4" },
  ],
  "6-11": [
    { title: "Computing Modified Duration", url: "https://youtu.be/PjDT0aZ2nd0" },
    { title: "Applications of Duration", url: "https://youtu.be/bsEJW-8et4o" },
    { title: "Money Duration and PVBP", url: "https://youtu.be/5SPJ2YRrziU" },
    { title: "Properties of Duration", url: "https://youtu.be/8O8u9QhQfW8" },
  ],
  "6-12": [
    { title: "Bond Convexity", url: "https://youtu.be/nluKGzsNlxo" },
    { title: "Convexity Adjustment", url: "https://youtu.be/eNwVM8pU0Uo" },
    { title: "Portfolio Duration and Convexity", url: "https://youtu.be/715P3D-nEbs" },
  ],
  "6-13": [
    { title: "Curve-based Interest Rate Risk Measures", url: "https://youtu.be/JxDGd7lIyds" },
    { title: "Key Rate and Empirical Duration", url: "https://youtu.be/DyWuY6sJlQ8" },
  ],
  "6-14": [
    { title: "Sources of Credit Risk", url: "https://youtu.be/igO5uCA8KzE" },
    { title: "Credit Rating Agencies and Credit Ratings", url: "https://youtu.be/OIz23rRR6vY" },
    { title: "Factors Impacting Yield Spreads", url: "https://youtu.be/3ZuunE6WeuY" },
  ],
  "6-15": [
    { title: "Sovereign Credit Analysis", url: "https://youtu.be/uR_HMx09U1k" },
    { title: "Non-sovereign Credit Risk", url: "https://youtu.be/Kqdy9y3zc6Q" },
  ],
  "6-16": [
    { title: "Assessing Corporate Creditworthiness", url: "https://youtu.be/YuEV7iNh7Bs" },
    { title: "Financial Ratios in Corporate Credit Analysis", url: "https://youtu.be/MEFhIw5Rzn4" },
    { title: "Seniority Rankings, Recovery Rates, and Credit Ratings", url: "https://youtu.be/LI6eGyb92C8" },
  ],
  "6-17": [
    { title: "The Benefits of Securitization", url: "https://youtu.be/7s9Jr84voKQ" },
    { title: "The Securitization Process", url: "https://youtu.be/87OErJTUAaE" },
  ],
  "6-18": [
    { title: "Covered Bonds", url: "https://youtu.be/KWvWywd2X10" },
    { title: "ABS Structures to Address Credit Risk", url: "https://youtu.be/RV31Gy_EWBg" },
    { title: "Non-mortgage ABS", url: "https://youtu.be/2fpkx055AUw" },
    { title: "Collateralized Debt Obligations", url: "https://youtu.be/q4xIElXqXaY" },
  ],
  "6-19": [
    { title: "Time Tranching", url: "https://youtu.be/fSoHPT9G69g" },
    { title: "Mortgage Loans and Characteristic Features", url: "https://youtu.be/z2DKjyr_UQ4" },
    { title: "RMBS", url: "https://youtu.be/tTCwE2H2uY4" },
    { title: "CMBS", url: "https://youtu.be/1s51hCr03mM" },
  ],

  // ===== VOLUME 7: DERIVATIVES =====
  "7-1": [
    { title: "Derivative Features", url: "https://youtu.be/Xx_PzFLh-yI" },
    { title: "Derivative Underlyings", url: "https://youtu.be/fJz9VVMEVi0" },
    { title: "Derivative Markets", url: "https://youtu.be/L9785JQm9RE" },
  ],
  "7-2": [
    { title: "Forward Contracts", url: "https://youtu.be/gmgkLxIapqE" },
    { title: "Futures Contracts", url: "https://youtu.be/I6nR8Muk3m0" },
    { title: "Swaps", url: "https://youtu.be/sxIz2rI2LVQ" },
    { title: "Options", url: "https://youtu.be/dQJ_1fUtzvo" },
    { title: "Credit Derivatives", url: "https://youtu.be/KP8d77cY_oY" },
    { title: "Contrasting Forward Commitments and Contingent Claims", url: "https://youtu.be/7KPMCmRSWzs" },
  ],
  "7-3": [
    { title: "Derivative Benefits and Risks", url: "https://youtu.be/8DTtolvBmu0" },
    { title: "Investor and Issuer Use of Derivatives", url: "https://youtu.be/7FS1BuEYkO8" },
  ],
  "7-4": [
    { title: "Arbitrage and Replication", url: "https://youtu.be/LSZimjDcjxE" },
    { title: "Cost of Carry", url: "https://youtu.be/72q21fWcMDc" },
  ],
  "7-5": [
    { title: "Pricing and Valuation of Forward Contracts", url: "https://youtu.be/I4kH5g_rBDY" },
    { title: "Pricing and Valuation of Interest Rate Forwards", url: "https://youtu.be/mR7VmdQgy9g" },
  ],
  "7-6": [
    { title: "Pricing Futures Contracts and MtM Valuation", url: "https://youtu.be/PQjXBYfDs3c" },
    { title: "Interest Rate Futures", url: "https://youtu.be/v94kaVPgQYE" },
    { title: "Forward and Futures Price Differences", url: "https://youtu.be/hKwLtUGHk98" },
  ],
  "7-7": [
    { title: "Swaps vs. Forwards", url: "https://youtu.be/r4JSosP2PGY" },
    { title: "Swap Value and Prices", url: "https://youtu.be/O9jlGVnU354" },
  ],
  "7-8": [
    { title: "Option Exercise Value and Time Value", url: "https://youtu.be/fSWehq6-UOk" },
    { title: "Factors Affecting Option Value", url: "https://youtu.be/0SEHJs6KKpY" },
  ],
  "7-9": [
    { title: "Put-call Parity", url: "https://youtu.be/Lb-lmjZ3xkA" },
    { title: "Put-call Forward Parity and Firm Value", url: "https://youtu.be/FyhBBAsF6Nk" },
  ],
  "7-10": [
    { title: "Using the Binomial Model to Price Options", url: "https://youtu.be/OMODAP8XsI4" },
  ],

  // ===== VOLUME 8: ALTERNATIVE INVESTMENTS =====
  "8-1": [
    { title: "Alternative Investments Features and Methods", url: "https://youtu.be/yi-dr9pR7us" },
    { title: "Alternative Investment Structures", url: "https://youtu.be/dMxiZKV8h4Y" },
  ],
  "8-2": [
    { title: "Alternative Investment Performance", url: "https://youtu.be/eVZCXZzhLfY" },
    { title: "Alternative Investment Returns", url: "https://youtu.be/m5LYbbUaMG4" },
  ],
  "8-3": [
    { title: "Private Equity", url: "https://youtu.be/h1V4lkEyqQs" },
    { title: "Private Equity Exit Strategies", url: "https://youtu.be/O9OsKk5Atbs" },
    { title: "Private Debt", url: "https://youtu.be/qR5W0WyYzMg" },
  ],
  "8-4": [
    { title: "Real Estate Investments", url: "https://youtu.be/yAZ1Gf17TsI" },
    { title: "Infrastructure Investments", url: "https://youtu.be/_xgUEnuKw0o" },
  ],
  "8-5": [
    { title: "Features of Natural Resources Investing", url: "https://youtu.be/25Vop6EowFI" },
    { title: "Commodity Investment Forms", url: "https://youtu.be/KKgELWb8oeg" },
    { title: "Natural Resource Investment Risk and Return", url: "https://youtu.be/eBmjZlIndmg" },
  ],
  "8-6": [
    { title: "Hedge Fund Features", url: "https://youtu.be/CZm_xh81ygo" },
    { title: "Hedge Fund Strategies", url: "https://youtu.be/SRzJYvLu0FY" },
    { title: "Hedge Fund Investment Forms", url: "https://youtu.be/9DMQejpYy34" },
    { title: "Hedge Fund Investment Risk and Return", url: "https://youtu.be/uUzejOEPxUg" },
  ],
  "8-7": [
    { title: "Distributed Ledger Technology", url: "https://youtu.be/ASnIZpngvos" },
    { title: "Features of Digital Asset Investing", url: "https://youtu.be/_OdboK3KnbA" },
    { title: "Digital Asset Investment Forms, Risks and Rewards", url: "https://youtu.be/WFqt3eCohao" },
  ],

  // ===== VOLUME 9: PORTFOLIO MANAGEMENT =====
  "9-1": [
    { title: "Risk, Return and Other Investment Characteristics", url: "https://youtu.be/1rmZLKHNk94" },
    { title: "Risk Aversion and Portfolio Selection", url: "https://youtu.be/sSWKH8VzrKg" },
    { title: "Utility Theory and Indifference Curves", url: "https://youtu.be/n1-GZ3mWRUw" },
    { title: "Portfolio Risk and Return", url: "https://youtu.be/PBrHLdkupv8" },
    { title: "The Power of Diversification", url: "https://youtu.be/MMzlfb6gFFE" },
    { title: "Efficient Frontier", url: "https://youtu.be/qWkgm43EyWg" },
  ],
  "9-2": [
    { title: "Capital Market Theory", url: "https://youtu.be/i9_kVsrQ5As" },
    { title: "Systematic Risk vs. Unsystematic Risk", url: "https://youtu.be/gEvB7vcpvso" },
    { title: "Return Generating Models", url: "https://youtu.be/54-oPF9PM7Y" },
    { title: "CAPM Beta Explained", url: "https://youtu.be/QwVb_4hEYjc" },
    { title: "Capital Asset Pricing Model", url: "https://youtu.be/byKfpFe-XfE" },
    { title: "CAPM – Undervalued and Overvalued Stocks", url: "https://youtu.be/mT3aroCeitc" },
    { title: "CAPM Limitations and Extensions", url: "https://youtu.be/SToWqnKGGNY" },
    { title: "Sharpe Ratio", url: "https://youtu.be/C-vje5xTwGY" },
    { title: "Treynor Ratio", url: "https://youtu.be/EL35RgePzHk" },
    { title: "M-squared (M2) Ratio", url: "https://youtu.be/8mP5GzGPGvM" },
    { title: "Jensen's Alpha", url: "https://youtu.be/v6FrqLGfQns" },
  ],
  "9-3": [
    { title: "Portfolio Perspective", url: "https://youtu.be/mEue9ilpO0w" },
    { title: "The Portfolio Management Process", url: "https://youtu.be/GCdnFGjFw9s" },
    { title: "Types of Investors", url: "https://youtu.be/KliJ4ZkQpBM" },
    { title: "The Asset Management Industry", url: "https://youtu.be/XVVLsgs2rI0" },
    { title: "Pooled Investments", url: "https://youtu.be/eISjlyP1FA8" },
  ],
  "9-4": [
    { title: "The IPS", url: "https://youtu.be/1rp2Wi9SdEE" },
    { title: "IPS Risk and Return Objectives", url: "https://youtu.be/Wm0xWzOxXZA" },
    { title: "IPS Constraints and Client Information", url: "https://youtu.be/e_FscldHgKE" },
    { title: "Portfolio Construction", url: "https://youtu.be/fuQAqHjWOlU" },
    { title: "ESG Considerations in Portfolio Construction", url: "https://youtu.be/U_Vyt0r6lyc" },
  ],
  "9-5": [
    { title: "Cognitive Errors – Belief Perseverance Biases", url: "https://youtu.be/lye0y1Ld8fI" },
    { title: "Cognitive Errors – Processing Errors", url: "https://youtu.be/1OEWwUWb558" },
    { title: "Emotional Biases", url: "https://youtu.be/qUju1VaXtR8" },
    { title: "Behavioral Finance – Market Anomalies", url: "https://youtu.be/S5gr7SjiYT8" },
  ],
  "9-6": [
    { title: "Risk Management Process", url: "https://youtu.be/DZ3hc0P_ylY" },
    { title: "Risk Management Framework", url: "https://youtu.be/mNm4ZTRWWH0" },
    { title: "Risk Governance – An Enterprise View", url: "https://youtu.be/ZK8vL3EatcY" },
    { title: "Risk Tolerance", url: "https://youtu.be/GrvbF0fXVC8" },
    { title: "Risk Budgeting", url: "https://youtu.be/yiX6x_ysB28" },
    { title: "Identification of Risk", url: "https://youtu.be/6nExDDuGzRE" },
    { title: "Risk Drivers and Metrics", url: "https://youtu.be/MUv1wmVYP8k" },
    { title: "Risk Prevention, Avoidance and Acceptance", url: "https://youtu.be/lf-qUdmt9TE" },
    { title: "Risk Transferring, Shifting and How to Choose", url: "https://youtu.be/LOYvSUhz7xI" },
  ],

  // ===== VOLUME 10: ETHICS =====
  "10-1": [
    { title: "Ethics and Trust in the Investment Profession", url: "https://youtu.be/0x081HGowmo" },
  ],
  "10-2": [
    { title: "Code of Ethics and Standards of Professional Conduct", url: "https://youtu.be/zGRPVrEh1Js" },
  ],
  "10-3": [
    { title: "Standard I(A): Knowledge of the Law", url: "https://youtu.be/syeNuv23LH0" },
    { title: "Standard I(B): Independence and Objectivity", url: "https://youtu.be/qay2LwSAxM8" },
    { title: "Standard I(C): Misrepresentation", url: "https://youtu.be/IeZIYXP47Xs" },
    { title: "Standard I(D): Misconduct", url: "https://youtu.be/ZMcJmBpGq34" },
    { title: "Standard I(E): Competence", url: "https://youtu.be/v5URX9c2hOQ" },
    { title: "Standard II(A): Material Nonpublic Information", url: "https://youtu.be/Yphbhu9h1Qs" },
    { title: "Standard II(B): Market Manipulation", url: "https://youtu.be/IQCNPmjaWvg" },
    { title: "Standard III(A): Loyalty, Prudence, and Care", url: "https://youtu.be/LN2kP3q6h1A" },
    { title: "Standard III(B): Fair Dealing", url: "https://youtu.be/jKyKYmFjnuQ" },
    { title: "Standard III(C): Suitability", url: "https://youtu.be/JvpNOOErqbc" },
    { title: "Standard III(D): Performance Presentation", url: "https://youtu.be/Icb4lofpUvw" },
    { title: "Standard III(E): Preservation of Confidentiality", url: "https://youtu.be/udp_g8LlsVo" },
    { title: "Standard IV(A): Loyalty", url: "https://youtu.be/l_pW893og3Y" },
    { title: "Standard IV(B): Additional Compensation Arrangements", url: "https://youtu.be/fXJ2zajasHA" },
    { title: "Standard IV(C): Responsibilities of Supervisors", url: "https://youtu.be/9H72qI7ZzQo" },
    { title: "Standard V(A): Diligence and Reasonable Basis", url: "https://youtu.be/3Y2FkRmcFBQ" },
    { title: "Standard V(B): Communication with Clients", url: "https://youtu.be/adbMP6uZeFU" },
    { title: "Standard V(C): Record Retention", url: "https://youtu.be/Vgv9C6lLG1k" },
    { title: "Standard VI(A): Avoid or Disclose Conflicts", url: "https://youtu.be/QtVXQI017ZQ" },
    { title: "Standard VI(B): Priority of Transactions", url: "https://youtu.be/2c0AHvbF2ug" },
    { title: "Standard VI(C): Referral Fees", url: "https://youtu.be/AqCWg8ZrjE4" },
    { title: "Standard VII(A): Conduct as CFA Participants", url: "https://youtu.be/4EdBZLoSdM4" },
    { title: "Standard VII(B): Reference to CFA Institute", url: "https://youtu.be/Rgs4DwmLX6c" },
  ],
  "10-4": [
    { title: "Global Investment Performance Standards (GIPS)", url: "https://youtu.be/k6A8b73ZtU0" },
  ],
  "10-5": [
    { title: "Ethics Application: Professionalism", url: "https://youtu.be/ErY-D8ccT2U" },
    { title: "Ethics Application: Integrity of Capital Markets", url: "https://youtu.be/YVRRlcBttQw" },
    { title: "Ethics Application: Duties to Clients", url: "https://youtu.be/ojKnFIHnsR8" },
    { title: "Ethics Application: Duties to Employers", url: "https://youtu.be/HbTI8m5jYjk" },
    { title: "Ethics Application: Investment Analysis", url: "https://youtu.be/ULgU7DaSFDs" },
    { title: "Ethics Application: Conflicts of Interest", url: "https://youtu.be/lgJgiaHLMsU" },
    { title: "Ethics Application: CFA Member Responsibilities", url: "https://youtu.be/SfkSjeAQWjg" },
  ],
};

function getVideoCount(key) {
  return VIDEO_LIBRARY[key] ? VIDEO_LIBRARY[key].length : 0;
}

function getTotalVideoCount() {
  return Object.values(VIDEO_LIBRARY).reduce((sum, vids) => sum + vids.length, 0);
}
